### ISSUE TITLE
Black screen on Chrome, Opera and IE 11

### ISSUE THREAD

**Issue by mdmcginn** [borismus/webvr-boilerplate#1]
Very cool! In the long run, of course, this should work on every major browser. Right now, I see a black screen on http://borismus.github.io/sechelt/ when I use Chrome Version 40.0.2214.93 (64-bit) and Internet Explorer 11 and Opera 27.0.1689.66 on Windows 7.

**Comment by borismus** [comment]
Strange, this definitely does not reproduce for me in Chrome. What OS are you running?

**Comment by mdmcginn** [comment]
Chrome Version 40.0.2214.94 m  (on Windows 7, on VirtualBox) and Chrome Version 40.0.2214.93 (64-bit) on Ubuntu 14.04

On Windows, Chrome says, "Rats! WebGL hit a snag." Ignore Reload. 
Choosing Reload gets the message "He's dead, Jim!"
Choosing Ignore gets the black screen.

Of course, my virtual hard drive is almost filled up, so that may cause memory problems (paging/swap).

**Comment by borismus** [comment]
Unfortunately don't have access to Windows/Linux at the moment, but can you
take a look in the console? Any errors? Try the Chrome Canary?

**Comment by mdmcginn** [comment]
Working fine after slight loading delay on Linux: Chrome Version
40.0.2214.111 and Chromium Version 40.0.2214.94 Ubuntu 14.10

**Comment by borismus** [comment]
Ok, thanks for checking.
