### ISSUE TITLE
Suggestion: Add webcam head tracking support when no VR headset is detected

### ISSUE THREAD

**Issue by akinnee** [borismus/webvr-boilerplate#10]
If there's no VR headset, in addition to using the mouse and keyboard to turn and move, it would be really cool to use webcam head tracking to change perspective/viewing angle.

Example: http://topheman.github.io/parallax/

**Comment by borismus** [comment]
Dupe: https://github.com/borismus/webvr-polyfill/issues/4

**Comment by akinnee** [comment]
Yep, thanks. I realized it was more appropriate in the polyfill repo.
