### ISSUE TITLE
Config should be passed as an argument as opposed to a global variable

### ISSUE THREAD

**Issue by zya** [borismus/webvr-boilerplate#100]
At the moment the config is a global variable `WebVRConfig`. It would be nicer if you could just pass it in as an argument to the manager. I think this also applies to `webvr-polyfill`. 

``` js
var manager = new WebVRManager(renderer, effect, options); 
```

**Comment by borismus** [comment]
The reason we currently use WebVRConfig is that the polyfill is completely
invisible to the developer.

All of the WebVRConfig options pertaining to the boilerplate could be
converted to an options array, but then there would be two different ways
of configuring.

**Comment by iambumblehead** [comment]
The polyfill is invisible to the developer and so the developer manages the visible and unusual step of defining a global configuration.
