### ISSUE TITLE
Canvas resized on every frame on Nexus 6

### ISSUE THREAD

**Issue by brianchirls** [borismus/webvr-boilerplate#104]
The following code in `resizeIfNeeded_` checks the size of the canvas against the desired value and resizes if they don't match:

``` javascript
  var size = this.renderer.getSize();
  if (size.width != window.innerWidth || size.height != window.innerHeight) {
  // ...
```

On the Nexus 6, for some reason, the `devicePixelRatio` is 3.5, which due to floating point shenanigans, causes three.js to report a height value of `386.85714285714283`. This never matches `window.innerHeight`, so a new render target is allocated, initialized (and garbage collected) on every single frame.

The height and width should be rounded when they're compared to the window dimensions, so this doesn't happen. This should probably be adjusted in `VREffect` as well. I'll post an issue there when I have a moment.

**Comment by ashconnell** [comment]
How do we know if it should be rounded up or down? 

I think we should be comparing to the previously stored canvas size and not the window - as this bug demonstrates the difference between an apple and an orange :-P

**Comment by brianchirls** [comment]
It's just rounded to the nearest value. It's what `Math.round` does.

The previous size _is_ the window size:

```
this.effect.setSize(window.innerWidth, window.innerHeight);
```

**Comment by borismus** [comment]
Good find, thanks. Would gladly take a PR :)

**Comment by brianchirls** [comment]
@borismus I'm happy to put one together - it's just a single line of code. But, since you don't have a CONTRIBUTING.md... should pull requests update the build as well?

**Comment by borismus** [comment]
Yes please. I'll work on a contributing

**Comment by brianchirls** [comment]
@borismus: will do.

Out of curiosity, why did you choose to check for resize on every frame, as opposed to only at the beginning and on resize/orientation events?

**Comment by borismus** [comment]
There were resize related bugs around orientation change. I think some race
conditions would happen in which the resize event came before orientation
re-layout. This seemed to solve the problem more robustly. I think the
round workaround you propose is a good one.

**Comment by brianchirls** [comment]
Yeah, I think `Math.round()` is fast enough that it's not a problem to run on every frame. It does make me a little sick that `getSize` allocates an object every time you call it, but three.js is full of those. I prefer the gl-matrix approach.

I should note that this problem only exists with the upcoming r74 version of three.js, as patched here:

https://github.com/mrdoob/three.js/commit/a17ea05be87ec68b08a68ebead09043f8d92cd5e#diff-c0e88b98497597a015ecf238e91ac3a0L352

This fix as I've proposed won't break anything in the meantime, and it'll just seamlessly kick in when the three.js upgrade happens. PR coming shortly...

**Comment by borismus** [comment]
Are you saying that this change here:
https://github.com/mrdoob/three.js/commit/a17ea05be87ec68b08a68ebead09043f8d92cd5e#diff-c0e88b98497597a015ecf238e91ac3a0L352
will
address the weird numerical issues you're seeing? If so, this
https://github.com/borismus/webvr-boilerplate/pull/107 is not worth landing.

**Comment by brianchirls** [comment]
No, I'm saying that change _caused_ the issue.

**Comment by borismus** [comment]
Right, ok. I think it makes sense to round the dimensions in three.js.
@mrdoob

**Comment by brianchirls** [comment]
Okay, why don't we do this - I'll file an issue over there and then maybe a PR if I get a positive response. Hopefully it'll get patched before r74 goes out. Let's leave this issue and PR open here in the meantime in case it doesn't.

**Comment by borismus** [comment]
Sounds great, thanks!

**Comment by brianchirls** [comment]
Closing because fixed in three.js https://github.com/mrdoob/three.js/issues/7995

**Comment by borismus** [comment]
Thanks!
