### ISSUE TITLE
5k Mac exposes WebGL screen limit for Chrome

### ISSUE THREAD

**Issue by pindiespace** [borismus/webvr-boilerplate#114]
I was experimenting with my boilerplate variant in a brand new 5K mac, and discovered that the images in stereo stretched across and past the right-hand side of the screen.

The reason? Chrome currently has a WebGL 4k limit, which was supposed to be removed...
https://codereview.chromium.org/1040153002

However, mayhaps it has not in my version.

Has anyone tested Firefox (which shouldn't show the problem) in a 5k Mac?

Ultimately VR is going to run on screens of this size - the current experience even on recent iphones is still "grainy."

**Comment by borismus** [comment]
Did you have a chance to explore this further? Also, it's unclear to me what webvr-boilerplate should do about this limitation.

**Comment by pindiespace** [comment]
An FYI, not anything that can be currently done. It does mean that high-res devices devoting more than 2k per eye might run into trouble.
