### ISSUE TITLE
Three.js r74 compatibility

### ISSUE THREAD

**Issue by florianmaxim** [borismus/webvr-boilerplate#115]
When I updated my project to Three.js' recent r70-Version the stereoscopic effect is gone.
(Testet on iPhone 6)

It seems like the screen is something like splitted..

Thanks for your amazing work!

**Comment by curti55** [comment]
same here. Seems the scene isnt rendererd per eye but stretched over whole width. just like there is no vreffect...

**Comment by crookookoo** [comment]
Same, one of the changes from r73 to r74 is breaking it.

**Comment by florianmaxim** [comment]
It works in Oculus Rift DK2 if that helps...

**Comment by crookookoo** [comment]
Tried updated VRControls and VREffect from this PR, doesn't seem to work on cardboard for me.
https://github.com/mrdoob/three.js/pull/8221

**Comment by cvan** [comment]
I'm not sure, and I haven't tested, but does it work at mrdoob/three.js@65d161e or mrdoob/three.js@a17ea05?

**Comment by crookookoo** [comment]
@cvan neither show correct distortion for right and left eye. In fact, I've tested previous versions of VREffect and webvr-manager.js that used to work with r73 and they too produce the same result, so I'm guessing the issue might be elsewhere.

(I'm testing in safari on iOS)

**Comment by florianmaxim** [comment]
Do you have lights in your scene that cast shadows?

When I turned the shadow castings of all lights off the VREffect worked again...

**Comment by rutkoski** [comment]
Probably related to https://github.com/mrdoob/three.js/issues/7732 ?

**Comment by crookookoo** [comment]
Can confirm that stereoscopic view breaks on boilerplate code with r74, looks like this:

![img_1420](https://cloud.githubusercontent.com/assets/5522686/13542101/d9121d72-e260-11e5-8e24-08e94f2a2b21.PNG)

Even though effect looks the same to what @rutkoski points, there are no lights or shadows in that code. Also tested without textures, and with freshly updated VRControls and VREffect.

@cheesyeyes can you share what you got working with r74?

**Comment by rutkoski** [comment]
Not working with r74, r75. Also, tried updating webvr-polyfill, not working either.

**Comment by crookookoo** [comment]
Try with polyfill and manager from 1.0 branch https://github.com/borismus/webvr-boilerplate/tree/webvr-1.0, the stereoscopic view works for me. 

The VR-view UI scales in a weird way and is not interactive, but this is going to be fixed before the merge hopefully.

**Comment by rutkoski** [comment]
Good to know it's beying fixed.

Would like to see integration with the effects composer also (that broke VR).
Has anyone been able to use post effects with the boilerplate?

**Comment by borismus** [comment]
@crookookoo Yes, there are some known issues with the 1.0 polyfill, but hopefully we will sort them soon: https://github.com/borismus/webvr-polyfill/issues/46. After that happens I will merge webvr-1.0 to master and things should be good again.

**Comment by borismus** [comment]
Alright, should be compatible now.
