### ISSUE TITLE
Support WebVR 1.0 API changes

### ISSUE THREAD

**Issue by cvan** [borismus/webvr-boilerplate#119]
Per https://github.com/borismus/webvr-polyfill/tree/webvr-1.0

**Comment by cvan** [comment]
And also three.js' https://github.com/mrdoob/three.js/blob/dev/examples/js/effects/VREffect.js and https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/VRControls.js have changed too

**Comment by borismus** [comment]
Yes. I have a few things on the backlog before merging:
- Polyfill samples: build a WebVR and a THREE.js sample into the repo.
- Boilerplate: inject UI into the polyfill element (if possible).
- Add viewer param event on window broadcasting DeviceInfo and ViewerInfo. (we're thinking `vrdisplaydeviceparamschange`)

**Comment by borismus** [comment]
Just to be clear, this merge to webvr-1.0 will also greatly simplify webvr-boilerplate: https://github.com/borismus/webvr-boilerplate/tree/webvr-1.0

**Comment by borismus** [comment]
Woot.
