### ISSUE TITLE
Example shows as black screen in Oculus Rift

### ISSUE THREAD

**Issue by brianchirls** [borismus/webvr-boilerplate#121]
Firefox Nightly now supports un-prefixed `requestFullscreen`, so when we attempt to enter VR mode, it gets called without a reference to the HMD.

Problem happens here:
https://github.com/borismus/webvr-boilerplate/blob/master/src/webvr-manager.js#L440

**Comment by borismus** [comment]
Tried with polyfill for WebVR 1.0? This pre-1.0 code is going away soon and
won't be maintained.

**Comment by brianchirls** [comment]
I was just looking into that. It's not clear what that branch is doing; github refuses to show the diff because it's too big with all the checked in node packages.

But that branch isn't working either, presumably for different reasons. In Firefox, I get an error because `VRDisplay` is not defined. In Chromium (WebVR 1.0/Oculus build), the VR button doesn't show up at all.

Was the intention to optionally support both APIs until Firefox gets the new one? I thought I read that somewhere.

**Comment by DaveDubUK** [comment]
Similar problem here; Trying to run latest webvr-boilerplate demo on Firefox nightly (48.0a1), Oculus runtime 0.8.0.0. Running on localhost: 

Steps: Click VR button -> Oculus doesn't turn on (i.e. orange light stays orange). Stereoscopic view visible in browser. Clicking gears gives two options: 'Cardboard I/O 2014' and 'Cardboard I/O 2015'. 

Tried: restarting Oculus runtime - no change

Tried: running version here: http://people.mozilla.org/~dietrich/webvr-boilerplate/ - on clicking VR button, I get the black screen as reported by others above.

Is the Oculus currently supported? If not, is this a temporary or longer term situation?

**Comment by borismus** [comment]
Does this happen without the boilerplate? Maybe FF Oculus is just broken. Does this version of FF support WebVR 1.0 already?

**Comment by kearwood** [comment]
The current Nightly FF build supports Oculus on 0.8+ for Windows and 0.5 for OSX.  I am working on WebVR 1.0 API support, but not yet shipped in FF Nightly.

You can follow the progress on 1.0 here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1250244

I was able to run the Link in DaveDubUK's comment above on a DK2 with the current Nightly, but I am running slightly newer Oculus runtimes.  Are you still seeing the issue?

**Comment by cvan** [comment]
opened PR #124 to address
