### ISSUE TITLE
if not using via node modules, correct way to include?

### ISSUE THREAD

**Issue by cindyloo** [borismus/webvr-boilerplate#122]
if I want to implement the boilerplate without requiring node.js, how do I do that?  I spent some time trying to figure out what/how things work and got it limping along.  However, the directory structure isn't a straight copy/paste.  Where should the assets for the buttons go, and how do I access the css (my background is a strange red when in vr mode) etc?

thanks

what I included:

//.includes
script src="js/src/webvr-polyfill.js"></script>
 script src="js/src/device-info-test.js"></script>
script src="js/src/webvr-manager.js"></script>

//setup
WebVRConfig = {
      // Forces cardboard distortion in VR mode.
      FORCE_DISTORTION: true, // Default: false.
      // Prevents cardboard distortion in VR mode
    PREVENT_DISTORTION: true, // Default: false.
      // Override the cardboard distortion background color.
    DISTORTION_BGCOLOR: {x: 1, y: 0, z: 0, w: 1}, // Default: (0,0,0,1).
      // Show eye centers (for debugging).
      SHOW_EYE_CENTERS: true, // Default: false.
    };  

//.. in init()

 effect = new THREE.VREffect(renderer);
         var params = {
          hideButton: false, // Default: false.
          isUndistorted: false // Default: false.
        };
        vrmanager = new WebVRManager(renderer, effect, params);

//in render()

 vrmanager.render(scene, camera);

**Comment by pindiespace** [comment]
You'll probably need to bite the bullet and use Node. A simple server - https://github.com/spadin/simple-express-static-server

**Comment by cindyloo** [comment]
the real issue is that I have a web host that doesn't support node.  I *could* host elsewhere, but I was hoping I wouldn't have to yet.. (ps am already using node for local dev)

**Comment by cindyloo** [comment]
FYI this was SO helpful: http://www.sitepoint.com/how-to-build-vr-on-the-web-today/.

**Comment by cindyloo** [comment]
I did get this working without needing to implement node.js on my web server, FYI.  just follow the link above.  Also, I did need to use webvr-boilerplate's VRControls and VREffects to get the gyroscope working in mobile/simulation...
