### ISSUE TITLE
Mobile has trouble with "forward" in landscape mode

### ISSUE THREAD

**Issue by scottgarner** [borismus/webvr-boilerplate#126]
I think this is actually an issue with the polyfill, When viewing the boilerplate demo on both iOS and Android devices, the rotating cube appears in front of me when holding the device in portrait mode.

When in landscape mode, the cube appears either 90 degrees to my left or right depending on whether I'm in landscape left or landscape right.

This happens even when I manually call for a resetPose. It seems that device orientation needs to be accounted for in the pose reset.

**Comment by borismus** [comment]
Could you log this against webvr-polyfill?

**Comment by scottgarner** [comment]
You bet.
