### ISSUE TITLE
Disabling distortion correction

### ISSUE THREAD

**Issue by scottgarner** [borismus/webvr-boilerplate#128]
What is the proper way to disable distortion correction now? Previously, you could set `PREVENT_DISTORTION` in `WebVRConfig`, but this no longer works.

**Comment by borismus** [comment]
Why do you want to disable distortion correction? If anything, this would go into the polyfill which now takes care of distortion.

**Comment by scottgarner** [comment]
Our project is abstract enough that it isn't necessary and there was a noticeable performance hit in the previous version with distortion correction enabled vs disabled.

**Comment by borismus** [comment]
Could you log a feature request against the polyfill to bring this back?

**Comment by scottgarner** [comment]
Sure.
