### ISSUE TITLE
glitchy left eye/view 

### ISSUE THREAD

**Issue by cindyloo** [borismus/webvr-boilerplate#129]
not getting any console errors in simulation: but the glitch happens on the iPHone 6 FF as well as simulation mode in Chrome and FF
you can go here to see the problem (make sure you enter simulation mode)
http://www.vrdoodler.com/doodleverse.html
and hit the cardboard view...

**Comment by cindyloo** [comment]
![screen shot 2016-04-04 at 8 29 21 am](https://cloud.githubusercontent.com/assets/659092/14247904/6e22a31e-fa3f-11e5-8b50-e0ac2c7599cc.png)

**Comment by borismus** [comment]
Not sure what's going on, but I think it's your code. In fullscreen mode I see this:

![screen shot 2016-04-06 at 12 02 54 pm](https://cloud.githubusercontent.com/assets/277632/14329267/87bd3670-fbef-11e5-9c79-cf32c5e9f852.png)

**Comment by cindyloo** [comment]
it actually works fine when you first come into fullscreen. Only after toggling into cardboard mode does the above happen in fullscreen mode.

no idea what the problem could be? my code isn't doing anything different than rotating your cube in your index.html example, other than that I'm drawing LineGeometries.... You can see the left eye kind of renders and kind of glitches. Could this be something around the scissoring or clearing the previous buffer?

**Comment by cindyloo** [comment]
it was this line in my code that was causing the left eye to glitch.
renderer.autoClear = false;
