### ISSUE TITLE
Updating controls flips image

### ISSUE THREAD

**Issue by higain** [borismus/webvr-boilerplate#138]
Hi, this might be a mistake in my thinking, but I have following problem with webVR.

I'm working on enabling a VR Option for gzweb (http://gazebosim.org/gzweb) and have come so far, that everything seems fine when the headset-position data is not used.
By adding the controls.update() function call, the whole image flips upside down, everything else works fine.

You can check out the code I've written here:
https://bitbucket.org/deltec/gzweb_webvr

To run gzweb install gazebo5 (not 6, not 7, those have problems with gzweb) and follow the steps in readme.

I really hope you can help me with this, I reached a dead end.
A hotfix by adding a matrix to flip the whole scene works but that shouldn't be the solution.

Thank you very much!
![image](https://cloud.githubusercontent.com/assets/17297249/14917975/f70baf22-0e21-11e6-9304-b449118bc70d.png)
![image](https://cloud.githubusercontent.com/assets/17297249/14917984/00938cae-0e22-11e6-8f20-c5dfef7e65b0.png)

**Comment by borismus** [comment]
What does this have to do with webvr-boilerplate? Closing since it seems like a webvr issue.
