### ISSUE TITLE
Adding an fps counter?

### ISSUE THREAD

**Issue by RuiOrey** [borismus/webvr-boilerplate#140]
Hi, I don't know if is interesting or in the scope of this project ... but would like to leave a suggestion of adding a flag to put some kind of fps counter on-screen..
Some way of benchmarking in several devices...

I'm using the regular stats.js but it disappears when entering vr mode in my mobile.

Thank you and greak work!

**Comment by borismus** [comment]
Sorry, out of scope. Take a look at @Toji's webvr-samples, he has a WebGL
based FPS counter.

**Comment by toji** [comment]
Specifically, you should be able to drop https://github.com/toji/webgl-utils/blob/master/src/wglu-stats.js into any project. It's completely standalone. Sample of how it's used: https://github.com/toji/webgl-utils/blob/master/stats-test.html

**Comment by RuiOrey** [comment]
Thank you!
