### ISSUE TITLE
Button Position: Why `position: fixed;`

### ISSUE THREAD

**Issue by Fischaela** [borismus/webvr-boilerplate#147]
Hey,

I just have a short question: Why are the buttons placed with `position: fixed;`? Wouldn't it be slightly better to use `position: absolute;`, so the buttons will be aligned relative to the parent element's dimensions? What are the downsides, am I overlooking something?

Cheers,
Michaela

![bildschirmfoto_2016-06-21_um_15_35_31](https://cloud.githubusercontent.com/assets/3409561/16231322/0427ac9c-37c6-11e6-8d9d-8460ff9c705f.png)

**Comment by borismus** [comment]
I think you're right. Especially if the canvas is not full screen. I'm open
to PRs.

**Comment by Fischaela** [comment]
Submitted PR #148
