### ISSUE TITLE
Line 158 of webvr-manager is missing something?

### ISSUE THREAD

**Issue by zen3d** [borismus/webvr-boilerplate#15]
Line 158 of webvr-manager.js reads:
   this.vrButton.offsetHeight;

Is that correct or is something missing? WebStorm flagged it as an expression statement which wasn't an assignment. 

But I'm not sure what would be correct in this context.

Also note that offsetHeight is not referenced anywhere else in that code (that I am able to find).

**Comment by brianpeiris** [comment]
Yeah, looks like incomplete code. You can ignore it though, it shouldn't have a negative effect.

**Comment by brianpeiris** [comment]
Oh, looks like it's not incomplete code. It's an intentional hack. Reading the offsetHeight forces Safari to re-calculate the layout: http://stackoverflow.com/a/3485654/22417

**Comment by zen3d** [comment]
Thanks, Brian.

I tried finding that stackoverflow reference indicated in the code (http://goo.gl/hjgR6r), but it didn't seem relevant. Your link above is relevant.

So it looks like offsetHeight is a getter that has a side-effect on Safari.
