### ISSUE TITLE
Multiple Renderers

### ISSUE THREAD

**Issue by devasur** [borismus/webvr-boilerplate#151]
Do you have any recommendations for how to go about modifying webvr-manager to accept two renderers - specifically an additional CSS3DRenderer ( or a second WebGLRenderer ? ).  I want to experiment with pixijs to add some good interaction for information display into scenes.  

Did see the demo that includes Wiki articles (Moose?).  Couldn't find the source.

**Comment by oguzgelal** [comment]
+1

**Comment by borismus** [comment]
Project intended as a simple demonstration. For more advanced usage, see webvr-polyfill, webvr.info, etc.
