### ISSUE TITLE
WebGL: INVALID_OPERATION when exiting VR mode in scene with no texture

### ISSUE THREAD

**Issue by Sam-Gr** [borismus/webvr-boilerplate#160]
If no texture is used in the scene, the following message appears in the console when exiting VR mode :
`WebGL: INVALID_OPERATION: drawArrays: no buffer is bound to enabled attribute`

You can easily reproduce this issue in the webvr-boilerplate test by commenting `map: texture,` in the index.html at line 132. Then, enter VR and exit VR with the "back" icon.

**Comment by borismus** [comment]
This isn't a boilerplate issue, but a THREE.js one.

**Comment by aramavetisyan** [comment]
@Sam-Gr  do you have any clue what causes this ? I have this problem now as well.

**Comment by grigorkh** [comment]
@Sam-Gr same here.

**Comment by Sam-Gr** [comment]
Actually, I can't reproduce the issue using the method that I described above. I guess the problem is fixed.
