### ISSUE TITLE
iOS - Motion Sickness

### ISSUE THREAD

**Issue by StudioZAAK** [borismus/webvr-boilerplate#17]
hi boris 

i'm currently comparing your webvr-boilerplate with the one from https://vr.chromeexperiments.com/ - i have set up two projects with the same content for each boilerplate - a skybox using 6x 1024x1024px textures. 

with your boilerplate on iOS (tested on iphone6+ and ipad air2 running both iOS 8.3 with google cardboard) the device orientation is not smooth (works fine on android / nexus 5) and it's not a fps issue. may it has something to do with gyro/motion sensor .. ? 

you can test it here (best with cardboard)

this is the project with your webvr-boilerplate:
http://zaak.io/prototypes/swiss/

same project with vr chrome experiments boilerplate:
http://zaak.io/prototypes/swiss3/

**Comment by borismus** [comment]
Hey ZAAK, yes indeed, thanks for reminding. this is because the chrome experiments boilerplate uses DeviceOrientationControls, which implement linear interpolation, and webvr-boilerplate doesn't. I think this feature is a good thing to add, will work on it shortly (adding it to the webvr-polyfill).

It's especially bad on iOS which has a 20 Hz update rate. On Android it's fine... will need to test it thoroughly, though.

**Comment by StudioZAAK** [comment]
what about a wurfl.js iphone detect to deviceorientation switch?

**Comment by borismus** [comment]
No need for wurfl (can be done much more easily), but that's also an
option. Smoothing may be OK on Android, though. Will have to test.

**Comment by borismus** [comment]
Hi ZAAK, could you try now? I've updated the boilerplate with interpolation.

**Comment by StudioZAAK** [comment]
thank you boris! 
i've tested SOOMTHING_FACTOR from 0 - 1 in 0.1 steps
0: like before
0.5 : best
all above 0.5 is like going back from 0.5 to 0 - so 1 is not super smooth it's like 0

here is a test with 0.5:
http://zaak.io/prototypes/swiss4/

compared to vr chromexperiments version it performs equal with 0.5 smoothing factor

is the smoothing linear ? 
i think exponential or cubic inOut smoothing would perform best 

![bildschirmfoto 2015-05-06 um 17 26 29](https://cloud.githubusercontent.com/assets/12050808/7496530/e20fb5d2-f414-11e4-950e-5e4bb072b81a.png)

![bildschirmfoto 2015-05-06 um 17 24 47](https://cloud.githubusercontent.com/assets/12050808/7496404/39979b54-f414-11e4-87d9-cc023f935ce1.png)

i also see that nosleep works on iOS now !

**Comment by StudioZAAK** [comment]
or a general motion blur?

**Comment by borismus** [comment]
Why do you think an easing function will yield better results? Also I doubt
that motion blur is a good idea, might be even more sickness inducing.

**Comment by StudioZAAK** [comment]
motion blur in general yes i would say that too.
but maybe to trigger it on a certain headmovement speed level could be a way to trick
the 20hz issue which is bad on fast head movements.

to easing function : when you enter a room you see for the first time (1) or when 
you enter a room that you already know (2) - the way you look/orientate is different.

1 the brain needs to scan the scene as whole thing > u need constant linear motion 
2 is more with easing as you know what’s around you - so head&eyes jump from 
A to B with speeding up the time between. 

so easing may be another way to trick update rates

looking for ways to fight that 20hz issue on iOS as it is important for webvr to run 
on each platform with best possible device responsiveness 

how would you trick it?

**Comment by borismus** [comment]
The way the linear interpolation works already handles large movements
pretty well. And actually iOS does a good job of providing events that are
accurate, so large deltas ate OK.

If you have time to explore better solutions that would be great. For now
I'm moving onto other improvements.

B

**Comment by StudioZAAK** [comment]
i'll give it a try soon

**Comment by borismus** [comment]
This should be fixed. With iOS 9 the update frequency is 60 Hz, and I just landed motion prediction, which hugely improves quality of head tracking. Re-open if you see issues.
