### ISSUE TITLE
Cube not visible on Firefox Android

### ISSUE THREAD

**Issue by autonome** [borismus/webvr-boilerplate#18]
1. Open http://borismus.github.io/webvr-boilerplate/ in Firefox on Android.
2. The page is visible, but the cube is not.
3. Touch the WebVR icon and nothing happens.

Notes:
- I'm using Cyanogen 12 (Lollipop) on a OnePlus One. I tried Firefox release and Nightly versions.
- Touching the WebVR icon gets this in the console: "TypeError: 'vrDisplay' member of RequestFullscreenOptions does not implement interface HMDVRDevice" on VREffect.js:97:3

**Comment by borismus** [comment]
Thanks for the report. Could you try in Chrome too?

**Comment by autonome** [comment]
Sure, filed #19 for that :) Cube is visible but not centered in default field of vision. Same result of nothing when clicking WebVR icon.

**Comment by autonome** [comment]
FTR the WebVR bit was happening because I didn't realize I needed to manually enable WebVR on Firefox Android. 

Now what happens is that the cube is only visible when I point the phone straight at the ground.

**Comment by borismus** [comment]
Odd -- it should show up at eye level. Does other content work right in FF
for Android?

**Comment by autonome** [comment]
Tried the MozVR panorama demo and the same thing happens. Looks like maybe a bug on our end :(

**Comment by borismus** [comment]
@autonome have you been able to get it to work?

**Comment by autonome** [comment]
Sorry for the delay. Just pulled latest from your master branch and:
- Firefox OS: Scene renders fine but no VR icon. There is a fullscreen
  icon. This is on nightly branch of Firefox OS.
- Firefox Android: Scene doesn't render, just a black screen shows, with
  the VR icon visible. I tried both release and nightly.

**Comment by autonome** [comment]
(Latest Android test is Nexus 5 running stock Lollipop.)

**Comment by autonome** [comment]
Update, I'd flashed both devices, so VR pref was disabled on both Android and Firefox OS. Pffft.

Results:
- Firefox OS: The cube is 90 degrees off. If you load the page with the phone 90 degrees from the ground (eg, you're upright and the phone screen is facing you), the cube becomes visible only when you point the screen 180 degrees from the ground. The VR icon was visible and worked!
- Firefox Android (nightly): Cube renders correctly and in the right place. The VR icon is not visible. Oddly, nothing renders when the pref is disabled, but once enabling it, the scene now renders, but no VR still.

**Comment by autonome** [comment]
Great, testing the next day on Firefox Nightly on Android and now the cube is doing the same thing as Firefox OS: Have to face the screen 180 degrees from the ground in order to see it.

@borismus Do you know where the code is that is doing orientation?

**Comment by brianpeiris** [comment]
@autonome Isn't this a Firefox problem? I've created a test that exhibits the problem in Nightly without using webvr-boilerplate or webvr-manager (just VRControls and VREffect from Three.js). As Vlad alluded to in the mailing list some months ago, you can workaround the problem by calling `resetSensor()`: http://output.jsbin.com/qobiqi/1

**Comment by autonome** [comment]
@brianpeiris It quite possibly is! I'm trying to narrow down where it's a problem on Firefox Android, and where we can work around that kind of problem in the boilerplate.

For example, it calling resetSensor() is the reasonable thing to do, should it always be called when boilerplate loads? Should it be called periodically? What are the downsides to resetting?

**Comment by brianpeiris** [comment]
The boilerplate shouldn't call resetSensor automatically at all. Perhaps it should give the user the option with another button or a calibration mode but we might be adding bloat at that point.

In anycase, this is just a workaround. Ideally the Firefox code should change so that it reports the correct orientation in the first place. If you _must_ workaround it, instead of fixing the bug, the correct place will probably be in VRControls, which is a dependency of webvr-boilerplate, that lives in [the Three.js repo](https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/VRControls.js).

**Comment by autonome** [comment]
Thanks Brian! I'll take a look. I can't really report the orientation
problem as a Firefox Android problem until I can narrow down exactly which
values are coming back bad, and from where.

**Comment by borismus** [comment]
The way you describe this with VR prefs, it's not a boilerplate issue at all, but a FF for Android issue. Closing for now. Please re-open if I misunderstood.
