### ISSUE TITLE
Cube not centered on Chrome in Android

### ISSUE THREAD

**Issue by autonome** [borismus/webvr-boilerplate#19]
1. Open http://borismus.github.io/webvr-boilerplate/ in Chrome on Android.
2. The page is visible, but the cube is off to the left.
3. Touch the WebVR icon and nothing happens.

Notes:
- Oh! Turns out I wasn't facing north. If I face north, the cube is centered ;)
- I'm using Cyanogen 12 (Lollipop) on a OnePlus One.

**Comment by borismus** [comment]
That's odd. Anything in the console?

**Comment by autonome** [comment]
Turns out WebVR mode did work, but was only visible once I turned my earthly vehicle towards magnetic north.

So, without WebVR, cube is off to the left. With WebVR, is magnetic north.

**Comment by borismus** [comment]
Got it. The boilerplate should have a background.

**Comment by autonome** [comment]
How will that fix the problem? Shouldn't the cubes be centered in the default field of vision?

**Comment by borismus** [comment]
This is precisely the reason for the problem: https://crbug.com/397824. Working on trying to find a workaround, stay tuned.
