### ISSUE TITLE
iOS?

### ISSUE THREAD

**Issue by greggman** [borismus/webvr-boilerplate#2]
The [cardboard demos](https://vr.chromeexperiments.com/) work on iOS but this doesn't?

Is that intentional? It's not clear from your description (or maybe I skimmed too much) how this is supposed to distinguish between a phone on it's own and a phone in a cardboard like holder. I thought maybe pressing the VR button that appeared but all that seemed to do is zoom rather than split the screen with a few for each eye.

Is this only supposed to work if you have WebVR.  Asking since like I mention the [cardboard demos](https://vr.chromeexperiments.com/) work on iOS even without WebVR which is a huge plus.

**Comment by borismus** [comment]
Definitely not intentional. This is one of the main points of the project, so thanks for noticing. I don't have an iOS device handy but once I do will resolve the issue.

**Comment by greggman** [comment]
Do you have a mac? Can you use the iOS Simulator?

It's buried inside XCode

![ios sim](http://blog.happyfuntimes.net/images/2014-12-gamejam/phone-sims.png)

I don't think there's a way to test orientation but you can at least see if you get a split screen

![screen shot 2015-02-03 at 16 31 19](https://cloud.githubusercontent.com/assets/234804/6032795/49db24b2-abc2-11e4-9c9a-b8a40fe73a68.png)

You might also find you need to move the VR button [because of this issue](http://stackoverflow.com/questions/26288076/how-to-get-safari-on-ios8-to-hide-the-toolbars-on-an-iphone-4-4s-5-5s).

**Comment by borismus** [comment]
I have access to an iOS device now, so will aim to fix this soon. What's the issue you're seeing? I'm not seeing errors, just a very zoomed-in view.

Also, looking to update the iconography and the icon positions shortly. The VR icon will go in the bottom-center of the screen.

**Comment by greggman** [comment]
I assumed if I clicked the VR button I should see a VR (split) view like the one above. Instead I get a single (not split) zoomed in view.

**Comment by borismus** [comment]
OK, this should be resolved, based on my simulator experiments. Could you test on an actual device?
