### ISSUE TITLE
Google Cardboard | Viewer Profiles

### ISSUE THREAD

**Issue by StudioZAAK** [borismus/webvr-boilerplate#20]
Is there a place where we can get all registered google cardboard viewer profiles?

**Comment by borismus** [comment]
What do you mean by this?

**Comment by StudioZAAK** [comment]
due to that google cardboard comes in many varieties - with the release of the WWGC (Works with google cardboard) program - each Google cardboard 'interpretation' can now be configured by scanning a QR code with the original cardboard app by google that set's your phone up with the cardboard version you have. here is the viewer profile configurator: (redacted) - just had a videochat with manfred/dontae but the two also didnt know and suggested to talk to you. so in this case we would need access to this viewer profile DB and push the values that are stored by device to a shader that handles all distortion corrections. as your boilerplate is just the best out there i think it would be necessary to integrate that somehow. if i would have access to this DB i could start working to add this feature to your boilerplate

**Comment by borismus** [comment]
So I'm working with a colleague on getting distortion correction landed
soon. As far as the Cardboard DB, I don't think we have one per se. The
viewer profile configurator creates a QR code that encodes all of the
parameters of the Cardboard-like device. We can read this QR code using web
tech. This would be a great project if you could help out.

The only difficulty is that this profile can only be stored per-domain as a
cookie. So you would have to do it for every new domain you go to...

**Comment by StudioZAAK** [comment]
great! so i start to work on implementing a QR Code reader to your boilerplate.
let's assume that you have a platform - you could store the profile in a user account setting ..

**Comment by borismus** [comment]
What do you mean by platform?

**Comment by StudioZAAK** [comment]
_a_ (django) _site to create_ (modified three.js editor) _\+ share_ (webvr-boilerplate) _webvr content_

**Comment by scottgwald** [comment]
Not sure if this belongs in the same Issue -- I tried the Cardboard I/O 2015 viewer profile, and it seemed inferior to the 2014 one when used with a 2015 viewer. May want to double check. Perhaps the 2014 and 2015 parameters got switched? I've been using the 2015 viewer exclusively, but it was only when I was experimenting with the profiles for the Gear VR (I have a hack for using WebGL with Gear VR, inquire if interested) that I noticed 2014 is the default, and tried the other one.

**Comment by borismus** [comment]
@scottgwald You're right. Something is off. The field of view / IPD do seem off especially on some phones. Investigating.

**Comment by idlewan** [comment]
Can confirm that the `Cardboard I/O 2015` profile is way too distorted.
I tested with this [I am cardboard v2](http://www.imcardboard.com/cardboard-vr-v2-box-85.html) and official google cardboard v1 (both look a lot more correct with the 2014 profile) on a Oneplus One and iphone 6 plus.

**Comment by borismus** [comment]
Even on the latest master? I checked in a potential fix last night

**Comment by idlewan** [comment]
Yes, even today on 69e972b.
Some screenshots:
- 2014 profile: looks okay-ish in cardboard v2
  ![screenshot_20151208-170240](https://cloud.githubusercontent.com/assets/632735/11662381/3e0a0f8c-9dce-11e5-91ad-4fda0c819a2f.png)
- 2015 profile: the universe is warping around me (in cardboard v2 or v1)
  ![screenshot_20151208-170301](https://cloud.githubusercontent.com/assets/632735/11662382/3e0a7d6e-9dce-11e5-99d4-d76bd016e43f.png)

I tried to have the top of the cube on the top edge of the vision to better compare the two.
I'm not sure what's the actual FOV of the 2015 profile, but it doesn't feel like it's 60 degrees.

**Comment by borismus** [comment]
Looks like you have distortion turned off. Have you set the
PREVENT_DISTORTION flag?

**Comment by idlewan** [comment]
I just checked, the WebVRConfig is empty (I am using the `index.html` from the repo for these screenshots).

If I put the `FORCE_DISTORTION` flag to `true`, I get similar results in terms of super-wide FOV (on the 2015 profile), but with the little black barrel border.
- 2014 profile:
  ![screenshot_20151208-174306](https://cloud.githubusercontent.com/assets/632735/11663322/75d0de32-9dd3-11e5-9ebc-5cc9e0f274dc.png)
- 2015 profile:
  ![screenshot_20151208-174249](https://cloud.githubusercontent.com/assets/632735/11663321/75cf2286-9dd3-11e5-833d-cfb94d59b035.png)

This is on the OnePlus One with Chrome v47.0.2526.76, if that has any influence. Similar results on Safari on iphone 6s plus.

**Comment by borismus** [comment]
Thanks for testing. This should now be fixed as of https://github.com/borismus/webvr-boilerplate/commit/efd177886484acefe935d072fc37670925c79982. Could you try again with the latest?
