### ISSUE TITLE
Crash in Firefox Nightly when entering VR mode

### ISSUE THREAD

**Issue by aleist** [borismus/webvr-boilerplate#24]
Entering VR mode in Firefox Nightly on my desktop (Ubuntu 14.10) crashes the browser. This happens independent of the CARDBOARD_DEBUG value, and independent of  whether the connected Oculus DK2 is turned on or off and the ovrd service is running or not. The demos on MozVR.com work fine.

I do get a message "Failed to load Oculus VR library!" when Firefox starts, which might be part of the problem, but I haven't figured out what to do about that yet. The OculusWorldDemo runs fine on the machine, so it's not a general problem with my Oculus installation.

On a side note, I am also not able to change the camera orientation with the mouse before entering fullscreen mode. This works in stable Chromium, along with fullscreen mode and CARDBOARD_DEBUG mode. I haven't tried the WebVR enabled Chromium build yet.

Any suggestions on how to fix this would be appreciated. Thanks!

The crash message:

AbortMessage: [11015] ###!!! ABORT: Invalid effect type!: file /builds/slave/m-cen-l64-ntly-000000000000000/build/src/gfx/layers/basic/BasicCompositor.cpp, line 441
Add-ons: %7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:41.0a1,webvr-addon%40mozvr.com:0.1.0
BuildID: 20150519030202
CrashTime: 1432091463
EMCheckCompatibility: true
EventLoopNestingLevel: 1
FramePoisonBase: 7ffffffff0dea000
FramePoisonSize: 4096
InstallTime: 1432089210
Notes: OpenGL: NVIDIA Corporation -- GeForce GTX 660/PCIe/SSE2 -- 4.5.0 NVIDIA 346.46 -- texture_from_pixmap
WebGL- libGL.so.1- libGL.so.1+ GL Context- GL Context+ WebGL+ xpcom_runtime_abort([11015] ###!!! ABORT: Invalid effect type!: file /builds/slave/m-cen-l64-ntly-000000000000000/build/src/gfx/layers/basic/BasicCompositor.cpp, line 441)
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: nightly
SecondsSinceLastCrash: 267
StartupTime: 1432091377
TelemetryEnvironment: 
Theme: classic/1.0
Throttleable: 1
URL: file:///data/third-party-projects/webvr-boilerplate/index.html
Vendor: Mozilla
Version: 41.0a1
useragent_locale: en-US

**Comment by borismus** [comment]
Interesting... I've never seen this before @vvuk any thoughts?

**Comment by borismus** [comment]
Closing. Please reopen if this is still a thing.
