### ISSUE TITLE
Keyboard and Mouse Control not Working in Desktop in Firefox

### ISSUE THREAD

**Issue by lunchboxav** [borismus/webvr-boilerplate#25]
Hi,

I use both the nightly and release version of Firefox and I can't seem to get input from keyboard or mouse. All I get is a slight up and down movement when using arrow keyboard button. This happen in Mac Yosemite.

Anyone has the same problem? Or is there any solution for it?

Feel free to test out here http://www.adityo.net/99names

**Comment by borismus** [comment]
This is happening because Firefox implements a getVRDevices call (but doesn't return any devices). Seems like a bad idea to me :( @vvuk is this deliberate?

**Comment by sbmadhav** [comment]
This seems ok now in Firefox version 39.0.3 (OS : Mac Yosemite). Both Keyboard and Trackpad seems to work.
