### ISSUE TITLE
Links to VRControls.js and VREffects.js not correct

### ISSUE THREAD

**Issue by emgeee** [borismus/webvr-boilerplate#27]
It would appear that the aforementioned files are currently out of date in the three.js master repo and the correct files are located on the `dev` branch or in the `js/deps` folder of this repo. I'd recommend updating the readme with a note about this as it does not work with the "latest" copy of three.

**Comment by borismus** [comment]
Yes, you're right. However, this will change as of THREE.js r72. This is a good reminder to merge the stable versions once r72 is released.

**Comment by borismus** [comment]
Logged a new bug for this: https://github.com/borismus/webvr-boilerplate/issues/31
