### ISSUE TITLE
My WebVR app looks weird on iOS

### ISSUE THREAD

**Issue by articulite** [borismus/webvr-boilerplate#28]
There is a skybox and it doesn't look how it looks on every other platform besides iOS. 

Not sure what is causing it.

http://alpha.vrchive.com/image2/Ou

**Comment by borismus** [comment]
Could you elaborate? What's the specific problem you're seeing? What makes you think this is a webvr-boilerplate issue and not a WebGL one?

**Comment by borismus** [comment]
If this is still happening, please re-open.

**Comment by articulite** [comment]
It is only for certain images in Safari I've noticed.

see: http://alpha.vrchive.com/image/OG

then compare to http://alpha.vrchive.com/image/dC

**Comment by borismus** [comment]
I can't reproduce in iOS 9. Also, please upgrade to the latest. There's a
pose predictor now which greatly improves head tracking (especially in iOS
9), where sensor update rate is high.

**Comment by articulite** [comment]
Ok will do! Thanks Boris!
