### ISSUE TITLE
Double manager

### ISSUE THREAD

**Issue by niccolomarcon** [borismus/webvr-boilerplate#29]
Is there any way to use two managers in the same time, one using the three.js renderer and one with the CSS3DRenderer.js renderer? I'm trying to emebed some html in my scene but when i enter in fullscreen the css renderer doesn't work.

Ty for your attention!

**Comment by borismus** [comment]
For this you'd probably need to modify the manager to call both renderers.
Or call the renderers directly rather than the one in the manager.

**Comment by niccolomarcon** [comment]
I will try! ty

**Comment by niccolomarcon** [comment]
I tried to call only the renderers but it didn't work. Now i'm trying to mod the manager to call both the renderers.

**Comment by borismus** [comment]
If you have questions, email me.

**Comment by sjcobb** [comment]
@niccolomarcon did you have any luck with this? I am trying something similar.

**Comment by niccolomarcon** [comment]
@sjcobb i'm sorry but honestly i don't remember and i don't own the code anymore.
