### ISSUE TITLE
Possible to render fullscreen on extended display

### ISSUE THREAD

**Issue by ghost** [borismus/webvr-boilerplate#32]
At the moment i am running a webapp and must drag the browser window to the extended HMD feed off screen. Is it possible, using WebVRManager to go into fullscreen mode on the extended HMD display while running the browser on a physical screen? help would be much appreciated.

**Comment by borismus** [comment]
Sounds like more of a requestFullScreen question than one that is specific to WebVR. From reading the [spec](https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Using_full_screen_mode), I don't think this is currently supported.
