### ISSUE TITLE
TypeError: 'vrDisplay' member of RequestFullscreenOptions does not implement interface HMDVRDevice.

### ISSUE THREAD

**Issue by 3demax** [borismus/webvr-boilerplate#34]
Hi, borismus! I'm trying to add FirefoxOS device (Alcatel 6015x) to supported devices but get the this error:
`TypeError: 'vrDisplay' member of RequestFullscreenOptions does not implement interface HMDVRDevice.`  

I have had to patch polyfill for proper uA detection 

```
diff --git a/src/webvr-polyfill.js b/src/webvr-polyfill.js
index cb2eb86..3eaa29a 100644
--- a/src/webvr-polyfill.js
+++ b/src/webvr-polyfill.js
@@ -73,7 +73,9 @@ WebVRPolyfill.prototype.getVRDevices = function() {
  */
 WebVRPolyfill.prototype.isMobile = function() {
   return /Android/i.test(navigator.userAgent) ||
-      /iPhone|iPad|iPod/i.test(navigator.userAgent);
+      /iPhone|iPad|iPod/i.test(navigator.userAgent) || 
+      /Firefox/i.test(navigator.userAgent)  || 
+      /ALCATELOneTouch6015X/i.test(navigator.userAgent);
 };

 WebVRPolyfill.prototype.isCardboardCompatible = function() {
```

Can you please look at changes to the code above and [my changes to boileplate](https://github.com/3demax/webvr-boilerplate/commit/613d23a796231a58a3a4155761b70eada94adbea?diff=unified)?
Just can't get what I'm missing.

**Comment by borismus** [comment]
Could you try without all of your other changes, just adding the ALCATEL device to the list of accepted ones?
