### ISSUE TITLE
WebVRManager doesn't play nicely with THREE.Mirror

### ISSUE THREAD

**Issue by RuiOrey** [borismus/webvr-boilerplate#36]
I'm trying to get a mirror effect working in a project that is using  [webvr-boilerplate](https://github.com/borismus/webvr-boilerplate).

I tried two ways:
1. use THREE.Mirror:

```
    verticalMirror = new THREE.Mirror( renderer, camera, { clipBias: 0.03, textureWidth: 256, textureHeight: 256, color:0x889999 } );

    verticalMirrorMesh = new THREE.Mesh( new THREE.PlaneBufferGeometry( 10, 10 ), verticalMirror.material );
    verticalMirrorMesh.add( verticalMirror );
    verticalMirrorMesh.position.y = 0;
    verticalMirrorMesh.position.z = 10;
    verticalMirrorMesh.rotation.y = 60;
    scene.add( verticalMirrorMesh );


    // Request animation frame loop function
    function animate( timestamp ) {

      verticalMirror.render();


      // Update VR headset position and apply to camera.
      controls.update();

      // Render the scene through the manager.
      manager.render( scene, camera, timestamp );



      requestAnimationFrame( animate );

    }
```

1. use THREE.CubeCamera (based on [Stemkoski's example](http://stemkoski.github.io/Three.js/Reflection.html)):

```
  var cubeGeom = new THREE.CubeGeometry(10, 10, 10, 1, 1, 1);
  mirrorCubeCamera = new THREE.CubeCamera( 0.1, 5000, 1024 );
  // mirrorCubeCamera.renderTarget.minFilter = THREE.LinearMipMapLinearFilter;
  scene.add( mirrorCubeCamera );
  var mirrorCubeMaterial = new THREE.MeshBasicMaterial( { envMap: mirrorCubeCamera.renderTarget } );
  mirrorCube = new THREE.Mesh( cubeGeom, mirrorCubeMaterial );
  mirrorCube.position.set(0,0,10);
      mirrorCube.rotation.y = 60;
  mirrorCubeCamera.position = mirrorCube.position;
  mirrorCubeCamera.rotation = mirrorCube.rotation;
  scene.add(mirrorCube);       


// Request animation frame loop function
        function animate( timestamp ) {

          mirrorCube.visible = false;
          mirrorCubeCamera.updateCubeMap( renderer, scene );
          mirrorCube.visible = true;


          // Update VR headset position and apply to camera.
          controls.update();

          // Render the scene through the manager.
          manager.render( scene, camera, timestamp );



          requestAnimationFrame( animate );

        }
```

In both cases, the render targets stops updating when activating VR Mode and stereo viewing is active.

Any thoughts of why this happens?

 [example](http://ruidorey.webfactional.com/) (messy code, sorry for that)

Thanks in advance.

**Comment by borismus** [comment]
Both examples yield the same behavior?

Could be something to do with applying this.distorter.preRender(); before
calling the render function on the VREffect. What if you tried something
like this:
1. preRender
2. mirror.render()
3. effect.render()
4. postRender

**Comment by RuiOrey** [comment]
Thank you for answering.
Similar. 
Keeps the last frame that was rendered before VR mode (from the render target camera). I did some similar to what you suggested before, inserting mirror.render() between all the steps.
Similar results.. 

Maybe something related with the camera, no?

http://ruidorey.webfactional.com/ <- I left this example also on stackoverflow with your suggestion

congratulations for this great project

**Comment by borismus** [comment]
Where is the mirror? Is it behind the viewer? To be honest, not sure that this is boilerplate related, probably a three.js question.

**Comment by RuiOrey** [comment]
Yes, behind the viewer/camera, need to rotate the view to see it. When looking at it in normal mode, the head is reflected in the mirror as rotating and moving. When changing to VR, it freezes... It seems the mirror camera stops rendering..
I'll expose the issue on three.js. 
Thanks

**Comment by brianpeiris** [comment]
This is a boilerplate issue after all, see [my answer to @RuiOrey's stackoverflow question](http://stackoverflow.com/a/32549777/22417). Mirrors don't work with CardboardDistorter since it intercepts `render` and forces the output to its own render target. This prevents mirrors from using their own render target. As I suggested on SO, you can work around this by temporarily restoring the original render function during the mirror rendering step.

We'll probably continue to need CardboardDistorter for iOS and IE support, so it should be able to handle mirrors without a workaround. Perhaps it would make sense to apply distortion patch via VREffect and leave the original renderer alone.

**Comment by RuiOrey** [comment]
Thank you

**Comment by borismus** [comment]
Ok, so to clarify: the issue is that CardboardDistorter doesn't properly handle three.js mirroring. Is this a CardboardDistorter issue or a VREffect one? Ie. does it reproduce without distortion?

**Comment by RuiOrey** [comment]
Well, if this is any useful, there is a set of two similar scenes I setup with a mirror (no effect and StereoEffect ). Added now other scene with VREffect. 

[1. mirror WITHOUT any effect - live example ](http://ruidorey.webfactional.com/mirror-test-no-stereo.html)  ![No Stereo](http://ruidorey.webfactional.com/nostereo.png)

[2. mirror WITH StereoEffect - live example](http://ruidorey.webfactional.com/mirror-test-stereo.html) 
![Stereo](http://ruidorey.webfactional.com/stereo.png)

[3. mirror WITH VREffect without CardboardDistorter - live example  ](http://ruidorey.webfactional.com/mirror-test-vr.html)  

I leave them here anyway if someone needs to check.

**Comment by RuiOrey** [comment]
Seems that the mirror works fine with VREffect and stereo active...
