### ISSUE TITLE
Judder experimented when looking around

### ISSUE THREAD

**Issue by ghost** [borismus/webvr-boilerplate#37]
Configuration : 
- Windows 8.1
- Oculus Rift DK2
- Runtime 0.6
- Chromium 44.0.2383.0

Reproduction steps : 
- Launch the example at /index.html
- Rotate the oculus by 90° with quick and repeated motion

Expected result : 
- The camera should look at the aim of the oculus in a smoothless fashion

Actual result : 
- Judders are experimented while doing the motion

Other informations : 
- I updated with the latest commits to experience this problem which I didn't have before. I tried to roll back to commit ae349e914e85e4887246108c4d36a3b8f6f3e74f and I don't experience the problem anymore.

Thanks for the amazing work though, all the other features are working neatly!

**Comment by borismus** [comment]
Confused by this one. If you have an Oculus plugged in, the polyfill shouldn't be enabled at all. I'm assuming you're using a WebVR-enabled browser build? Could you try testing again, this is very mysterious?

**Comment by ghost** [comment]
I'm using the chromium webVR enabled version yes. And I do reproduce, it's like the camera would try to get rotation information that it has trouble to have when the oculus is not facing or moving too quickly?

**Comment by borismus** [comment]
Could you capture a video? The polyfill should not enabled in that case, so
you should log a bug against the WebVR implementation.

**Comment by ghost** [comment]
I'll try to do that tonight, thanks for the attention!

2015-09-15 18:40 GMT-07:00 Boris Smus notifications@github.com:

> Could you capture a video? The polyfill should not enabled in that case, so
> you should log a bug against the WebVR implementation.
> 
> On Tue, Sep 15, 2015 at 6:36 PM tbalouet notifications@github.com wrote:
> 
> > I'm using the chromium webVR enabled version yes. And I do reproduce,
> > it's
> > like the camera would try to get rotation information that it has trouble
> > to have when the oculus is not facing or moving too quickly?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/borismus/webvr-boilerplate/issues/37#issuecomment-140594861
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/borismus/webvr-boilerplate/issues/37#issuecomment-140595427
> .

## 

http://www.beloola.com
_Thomas BALOUET  http://beloola.com/balou
http://www.twitter.com/thomasbalou_*
https://fr.linkedin.com/in/thomasbalouet*
_VR CREATIVE ENGINEER @Beloola_
_Tel :_ +33 (0)651-886-140

**Comment by ghost** [comment]
Hey, I uploaded a video here : you can see that it seems okay for a certain time but by doing the same movement at some point it jumps out : 
https://youtu.be/SxshFTmSv4Q
Thank you for looking it out!

**Comment by borismus** [comment]
This is likely not a WebVR boilerplate issue, but something with the underlying Chrome/FF implementation. Unless you have a reason to think it's boilerplate-specific, in which case please re-open.
