### ISSUE TITLE
Firefox Nightly not Rendering Correctly on `master`; Chromium not working on `gh-pages`

### ISSUE THREAD

**Issue by rudyjahchan** [borismus/webvr-boilerplate#4]
When on the `master` branch of this repo (and time of this writing), viewing on Firefox nightly results in a view not rendering properly. While it looks like a distortion is being correctly applied, the view appears to not render the left and right eye properly. Examples:

The provided simple Scene
![screen shot 2015-03-06 at 11 58 24 pm](https://cloud.githubusercontent.com/assets/107783/6540630/46f0a53e-c45d-11e4-90f0-1d44dc255b03.png)

Sechelt Port
![screen shot 2015-03-07 at 12 02 15 am](https://cloud.githubusercontent.com/assets/107783/6540631/5c797bec-c45d-11e4-8101-65d7156b5a15.png)

A Colleague's Demo made from the master
![screen shot 2015-03-06 at 11 57 56 pm](https://cloud.githubusercontent.com/assets/107783/6540634/802fa80e-c45d-11e4-93f4-7e2b08baa518.png)

This problem appears to be fixed on the `gh-pages` branch for Firefox Nightly **BUT** appears to cause Chromium to crash.

**Comment by jcarpenter** [comment]
> This problem appears to be fixed on the gh-pages branch for Firefox Nightly

Hmm, I'm still seeing the issue on Firefox Nightly, OSX, 39.0a1 (2015-03-09)

**Comment by rudyjahchan** [comment]
@jcarpenter On the `gh-pages` branch or on the PR I submitted?

**Comment by jcarpenter** [comment]
Ah, missed your two PRs. With them this is looking good on my end.

**Comment by rudyjahchan** [comment]
Closing this as the error in Chromium seems to be an issue with applying a contrast filter to an SVG image. Already opened an issue with the Chrome WebVR project and investigating workarounds.
