### ISSUE TITLE
Setting renderer.shadowMap.enabled = true breaks VR split-screenmode

### ISSUE THREAD

**Issue by kosso** [borismus/webvr-boilerplate#40]
Hi,
I've found that setting renderer.shadowMap.enabled = true, to enable shadows to be seen, breaks the VR/cardboard split-screen mode

Tested with r72 and r73 of three.js

Here's a test showing the basic boilerplate example, with an added ground plane and spotlight to create a shadow of the cube. https://kosso.co.uk/vr/boilerplate/index.html 
- Open in mobile Safari. Rotate to landscape.  
- Tap the corner icon once, to view the Cardboard icon. 
- Tap the cardboard icon to go to VR/Cardboard mode.

The scene is not correctly split in two. 

Here's an example with `renderer.shadowMap.enabled = true;` commented out.  https://kosso.co.uk/vr/boilerplate/noshadows.html

ps: When in the split-screen mode, I would like to remove the back arrow. It's not needed then. Surely, rotating the device back to portrait is enough to bring the buttons back if needed? 

thanks!

**Comment by nickjs** [comment]
I'm also seeing this: shadows disable double scene rendering. I worked around it with this brutal, ugly hack I would love to kill :)

``` javascript
    var orig = this.vrmanager.onVRClick_
    this.vrmanager.onVRClick_ = () => {
      this.renderer.shadowMap.enabled = false
      orig.call(this.vrmanager)
    }
```

**Comment by brianchirls** [comment]
See the issue @borismus just referenced. I'm afraid this can't be fixed here and has to wait for a patch to three.js.

In the meantime, if you really need shadows, you can disable Cardboard distortion. I tried hacking around it by overriding the three.js shadow map renderer, but it was horribly ugly and didn't work if you added any new lights after the first render.

**Comment by borismus** [comment]
Is this fixed as of THREE r75?

**Comment by brianchirls** [comment]
Yup. I've got shadows working just fine.
