### ISSUE TITLE
No VR distortion when entering VR mode

### ISSUE THREAD

**Issue by caseyyee** [borismus/webvr-boilerplate#45]
Entering VR mode on desktop doesn't enter with distortion.

(Mac OS, 0.5 runtime)

**Comment by caseyyee** [comment]
The VR button is only enabled after you enter fullscreen.  This means that we would be requesting Fullscreen w/vrDisplay option after Fullscreen has already happened.  This unfortunately won't work.   

The solution may be to move the VR goggles icon up along side the fullscreen icon.   This way requestFullscreen is made with the vrDisplay option (that enables the platform/driver distortion) What do you think @borismus?

**Comment by borismus** [comment]
Are you using a WebVR build? Have you tried with `WebVRConfig.FORCE_ENTER_VR = true`?

**Comment by caseyyee** [comment]
Yup, I'm trying this with Chromium with enable-webvr flag set and Firefox with the dom.vr.enabled = true.

I'm not aware of a `WebVRConfig.FORCE_ENTER_VR`  Where is that config found?   I looked in both the polyfill and boilerplate.

**Comment by caseyyee** [comment]
Ah found it.   Still the same result though.

**Comment by borismus** [comment]
For distortion, try with force enable distortion. It's a boilerplate
config. Ah but maybe not checked in. Also, likely adding an enter VR mode
button from non full screen view

**Comment by Willfire19** [comment]
For theVR button in non full screen view, for a quick and dirty job, you could just add the ability to pass a class to the created vr button. That way, developers can just position the button any way they like using css or jquery.

**Comment by borismus** [comment]
(It's checked in now). 

@Willfire19 yes, that probably makes sense to add to the webvr-manager.js configuration. Would gladly accept a PR :)
