### ISSUE TITLE
Windows Phone oscillations

### ISSUE THREAD

**Issue by RuiOrey** [borismus/webvr-boilerplate#46]
Hi, in Windows phone there is a lot of vibration and no stable image in the examples. 
It rotates correctly but a lot of trembling. 
Tested with a Lumia 640 and 930.

**Comment by borismus** [comment]
Please send a video. I don't know what you mean.

**Comment by RuiOrey** [comment]
Ok,sorry I noticed that this only happens with 640. with 930 sometimes before loading everything...640 maybe for not having all the sensors. closing the issue

**Comment by borismus** [comment]
What are 640 and 930?

**Comment by RuiOrey** [comment]
Lumia 640 and lumia 930.
