### ISSUE TITLE
Chromium for android crashes

### ISSUE THREAD

**Issue by varunsaravagi** [borismus/webvr-boilerplate#49]
I downloaded ChromePublic_Tango_1.19.apk from this link (https://drive.google.com/folderview?id=0BzudLt22BqGRbW9WTHMtOWMzNjQ&usp=sharing#list). I installed it on Nexus 6 but when I open it, it crashes. Is their device compatibility issues? It would be great if you can help me around since I need to use WebVR for a class project.

**Comment by borismus** [comment]
Try the non tango build.

**Comment by varunsaravagi** [comment]
Thanks. The other build works.
