### ISSUE TITLE
Samsung Gear VR?

### ISSUE THREAD

**Issue by flowida** [borismus/webvr-boilerplate#50]
I just wanted to know if all of this works with a samsung gear vr headset? Thanks!

**Comment by SpamLicker** [comment]
If you push the micro-USB plug out the way when you put your phone into the GearVR it'll work!

**Comment by flowida** [comment]
Okey, thanks! So then it's like any other 'manual' cardboards. 
There is no way to avoid android calling the oculus app when you connect your phone to the gear?

----- Ursprüngliche Nachricht -----
Von: "Carl Guyenette" notifications@github.com
Gesendet: ‎28.‎10.‎2015 13:11
An: "borismus/webvr-boilerplate" webvr-boilerplate@noreply.github.com
Cc: "flowida" flowida@googlemail.com
Betreff: Re: [webvr-boilerplate] Samsung Gear VR? (#50)

If you push the micro-USB plug out the way when you put your phone into the GearVR it'll work!

**Comment by SpamLicker** [comment]
You can do this!:
https://www.reddit.com/r/GearVR/comments/3c061s/cardboard_on_gear_vr_for_s6_easy_nonroot_solution/

**Comment by brianpeiris** [comment]
Yeah, it's not user-friendly at all and it basically just turns the GearVR into an expensive Cardboard device. WebVR browsers don't have access to the high-frequency tracking sensors or the Oculus rendering pipeline (timewarp, direct rendering, CPU and GPU priority, etc) but at least it's something. 

You can also enable low-persistence with these instructions: https://www.reddit.com/r/WebVR/comments/3mt8t2/using_webvr_with_the_gear_vr_headset/
