### ISSUE TITLE
Automatically change to VRControls

### ISSUE THREAD

**Issue by SpamLicker** [borismus/webvr-boilerplate#51]
I feel it would be good functionality to have the option to automatically change the controls to VRControls when entering VR mode and disabling then when exiting. I'm developing an app that can jump into VR mode intermittently and enabling the controls and disabling them is becoming problematic with all the different ways VR mode can exited (ESC on desktop, back button on Android etc).

**Comment by SpamLicker** [comment]
Is there a variable to detect if either Immersive mode or VR mode is active?

**Comment by borismus** [comment]
Could you clarify what you're trying to do? Take a look at what
webvr-manager does to go between Normal, Magic Window and VR modes.

**Comment by SpamLicker** [comment]
Thanks for replying :)
I'm trying to change the controls to VRControls when webvr-manager has activated any of the viewer modes it manages and change back to OrbitControls when that viewing mode has been deactivated. I just need a variable inside webvr-manager to make global so I can detect these two states. Is there anything?

**Comment by SpamLicker** [comment]
So I want to know when "Normal" mode is showing, or when either "Magic Window" or "VR" modes are showing so I can change the controls accordingly.

**Comment by borismus** [comment]
Why do you need this? The polyfill provides virtual VRDevices for non-VR
modes too.

manager = new  WebVRManager()
manager.mode is the current mode

**Comment by SpamLicker** [comment]
I need it to go back to the regular (non-stereoscopic) view and have the OrbitControls re-activate when I do. manager.mode does not change, it just tells me what kind of device I am using. 
When VREffect is active I want VRControls; when it is not active I want OrbitControls.

**Comment by SpamLicker** [comment]
I've added a variable within VREffect to be able to detect the switch so it now works. I still think it would be great to have this variable accessible within webvr-boilerplate. :)

**Comment by tommytee** [comment]
I there a way to bring the browser directly in to (a) stereoscopic VR mode without the need for button clicks?
If not is there a way to do it with a single click?

**Comment by borismus** [comment]
@Carl Ok, so you want to be able to pan with touch? This is sort of
implemented (yaw only) by default already (see
https://github.com/borismus/webvr-polyfill/blob/master/src/touch-panner.js).

@Tommy This was recently implemented.

**Comment by borismus** [comment]
Also note that there is now a `manager.isVRMode()`, and the `modechange` event. See docs: https://github.com/borismus/webvr-boilerplate/blob/master/README.md
