### ISSUE TITLE
Change in behaviour for DK2 VR headsets?

### ISSUE THREAD

**Issue by jbroberg** [borismus/webvr-boilerplate#52]
Hi there

Love the library, we use it and the polyfill extensively. I have leveraged it here:
https://github.com/MetaCDN/videojs-vr

I have noticed a change in behaviour in recent versions for the DK2 which is a bit of a negative for us.

Previous versions (< 1.2) were able to 'cast' directly to the Oculus Rift DK2 in direct rendering mode on chromium and firefox nightly w/ VR enabled, which was fantastic. You hit the VR button, a warning came up like it was a native app at the beginning, and it worked & looked great.

e.g. try this link with a DK2 plugged in (I'm running Oculus SDK 0.8, Windows 10,  chromium vr build or firefox nightly w/ VR enabled):
https://s3-ap-southeast-2.amazonaws.com/quicktest-metacdn/vr3.html

The new 0.2.0 behaviour is fantastic with cardboard but not great with DK2.  At one point I was getting cardboard instructions on desktop but I believe this has been resolved in recent commits.

This is with 0.2.0 of the new libs
https://stage.metacdn.com/r/v/vorjbrr/GKIb3Gc/embed?cachebust

The VR button now does side by side rendering on the main monitor. I presume this might still work in extended mode but most folks have moved (really, have been forced to move via SDK changes) to direct mode. Is there any way to get this behaviour back?

cheers

James

**Comment by brianpeiris** [comment]
It's a bug. I've fixed it in my pull request.
