### ISSUE TITLE
THREE.DoubleSide rendering incorrectly

### ISSUE THREAD

**Issue by SpamLicker** [borismus/webvr-boilerplate#55]
Since updating to version 0.2 THREE.DoubleSide seems to be rendering incorrectly in VR mode for me (on cardboard), the BackSide will often be rendered in front of the FrontSide. It's inconsistent. Is this happening with anyone else?

**Comment by tommytee** [comment]
I am also having this issue.  For me it seems as if the z-order is backwards in VR mode.

**Comment by SpamLicker** [comment]
Glad to see I'm not alone :)
It seems to be something to do with setting renderer.autoClear = false;
For me at least

**Comment by SpamLicker** [comment]
I'm rendering multiple scenes on top of each other and the VR the right eye is only rendering the last scene, even when I'm using renderer.clearDepth(); between each scene render.

**Comment by tommytee** [comment]
right now i am placing a simple box in front of another and the z order is backwards.  WebGLRenderer
renderer = new THREE.WebGLRenderer( { antialias: true } )

**Comment by tommytee** [comment]
nobody else?

**Comment by tommytee** [comment]
moving to new issue

**Comment by borismus** [comment]
Thanks for the reduced test case. Does this only happen with DoubleSide, or
also with FrontSide/BackSide too?

**Comment by tommytee** [comment]
It happens with FrontSide also.
its more obvious with DoubleSide because a cube's rear wall will appear in front.

**Comment by borismus** [comment]
Strange... I wonder what the deal is here! @mrdoob, any ideas?

**Comment by brianpeiris** [comment]
@SpamLicker Which browser are you seeing this in? Can you provide a test case?

**Comment by SpamLicker** [comment]
I only see it in the latest Chrome for Android (not Dev just regular) and only in the VR view mode. It's not consistent with all polygons, some will appear behind correctly and others will appear in front but they certainly seem to be grouped in some way. I'll provide an image when I get a chance. (Please ignore my right eye problem I mention above, it's a separate issue involving VREffect.js I think)

**Comment by mrdoob** [comment]
@borismus 

> Thanks for the reduced test case. 

Where can I see the reduced test case?

**Comment by tommytee** [comment]
issue #57 
http://postfat.ninja/

**Comment by tommytee** [comment]
here is the boilerplate with DoubleSide added to cube:
http://postfat.ninja/boiler.html

**Comment by mrdoob** [comment]
Right right. So the z-buffer is inverted.

![screenshot_20151109-122819](https://cloud.githubusercontent.com/assets/97088/11041087/b347a230-86dd-11e5-830d-11ee4b170153.png)

If this happened in all browsers I would think that it's a bug in three.js, but I suspect this is something in Chrome/WebVR.

/ping @toji

**Comment by toji** [comment]
Which builds do you see this happening with? The Windows Oculus or Vive builds? Android Dev? Only with the polyfill? I'm going to guess that if it's a WebVR experimental build then there's probably a bit of state that needs to be restored that I'm missing.

**Comment by tommytee** [comment]
here is what i checked, plus from mr doob

problem - Safari iOS 9.1
problem - chrome 46.0.2490.73 iOS 9.1
probelm - chrome 46.0.2490.76, Android 6.0.0; Nexus 5 Build/MRA58K
problem - chrome 46.0.2490.76 android 5.1.1 SM-G920V LMY47X - Galaxy S6
problem - chromeDev 48.0.2553.4 android 5.1.1 SM-G920V LMY47X - Galaxy S6
problem - Opera Beta 33.0.2002.97240 android 5.1.1 SM-G920V LMY47X - Galaxy S6

fine ----- Opera Beta 33.0.2002.97240 android 5.1.1 ONE A2005 LMY47V
fine ----- chrome 46.0.2490.76 android 5.1.1 ONE A2005 LMY47V
fine ----- chrome 46.0.2490.76 android 4.2.1
fine ----- chrome 43.0.2357.92 android 4.4.2

also tried r72 and latest r74 (on iOS)

**Comment by toji** [comment]
Hm... the fact that it's happening on iOS at all is concerning, and mean's it probably isn't some internal WebVR state like I was thinking.

**Comment by mrdoob** [comment]
I haven't tested it, but my bet is the `depthBuffer: false` in [this line](https://github.com/borismus/webvr-boilerplate/blob/6f13d114042ed14569a92eabd766479b7cd3355a/build/webvr-manager.js#L262) introduced by @njam in #35.
Try removing it (I think the one in `cardboard-distorter` can stay).

**Comment by tommytee** [comment]
that fixed it for me.  sweet. thanks

**Comment by njam** [comment]
Sorry about that! -> https://github.com/borismus/webvr-boilerplate/pull/61

**Comment by borismus** [comment]
Thanks!
