### ISSUE TITLE
Latest (Dec 30th 2014) Chromium WebVR build crashes out

### ISSUE THREAD

**Issue by rudyjahchan** [borismus/webvr-boilerplate#6]
Due to call to use of `webkitFilter` on the new SVG icons, the latest Chromium WebVR build crashes out on page load. A separate issue has been filed for that project, though given it may be awhile before it's addressed and people upgrade, a workaround may be in order.

**Comment by borismus** [comment]
I haven't been able to reproduce this, so closing.
