### ISSUE TITLE
Effect Scale is wrong

### ISSUE THREAD

**Issue by ghost** [borismus/webvr-boilerplate#65]
Hi, I am relatively new to three.js and webvr-boilerplate.

I implemented it and its great but, when I click the button at the bottom to move into fullscreen stereoscopic view, the scale of the two view effect is wrong, both eye screens appear very small and in the centre so when viewed through the oculus rift it is useless. The only work around I have found is to use the browser zoom to zoom into the correct level to line the eyes up
This however affects the quality of the graphics.

Is there any way to adjust the scale of view before the view is rendered so zooming is not necessary?

thanks :)

**Comment by borismus** [comment]
Please add a screenshot. What OS/browser?

**Comment by ghost** [comment]
[image: Inline image 1]

zoom at 100%

[image: Inline image 2]

zoom 150%

the first one is normal zoom but does not line up with the eyes.

the second one works but requires zooming which degrades quality.

thanks for your speedy response :) can anything be done?

**Comment by brianpeiris** [comment]
@tomcon25 Your images didn't come through. Also please mention your OS and browser, unless it's obvious from the screenshots.

**Comment by ghost** [comment]
---------- Forwarded message ----------
From: Tom Connolly tom.connolly2511@gmail.com
Date: Fri, Nov 13, 2015 at 2:55 PM
Subject: Re: [webvr-boilerplate] Effect Scale is wrong (#65)
To: borismus/webvr-boilerplate <
reply@reply.github.com


[image: Inline image 1]

zoom at 100%

[image: Inline image 2]

zoom 150%

the first one is normal zoom but does not line up with the eyes.

the second one works but requires zooming which degrades quality.

thanks for your speedy response :) can anything be done?

**Comment by borismus** [comment]
Still don't see the images, please try again.

**Comment by ashconnell** [comment]
Try uploading to imgur and putting the links in your comment

**Comment by ghost** [comment]
sorry for the delay been super busy recently, thank you though

this is with zoom at 125% with degraded graphics
http://imgur.com/QUCQ4T7

and this is with zoom at 100% but displays are too small to line up with
 the eyes for the oculus rift properly
http://imgur.com/zLp9n6R

any ideas on how to fix this?

thanks,
Tom

**Comment by borismus** [comment]
So, if this is a rift-specific issue, it's likely bypassing the boilerplate completely. Depending on if you're using FF or Chrome, you should log an issue with @vvuk or @tojiro.
