### ISSUE TITLE
A way to set specific canvas size if VR isn't available?

### ISSUE THREAD

**Issue by pindiespace** [borismus/webvr-boilerplate#66]
I've just started experimenting with the boilerplate, and ran into the following issue. If VR is unavailable there may be good reasons to fall back to the mono 3d canvas, embedded within a DOM element on a 2d browser page. However, the resize always goes to window .innerWidth and .innerHeight. So, in other words boilerplate assumes you always want to fill the screen with the 3d canvas. Resizes via three.js get overridden. 

Better Ux would allow graceful decay into a defined smaller size, as a child element in markup, instead of assuming it is the only thing in the page body. This is consistent with interfaces that follow "progressive enhancement" and use existing markup elements as the base for building the VR display. -pete

**Comment by borismus** [comment]
I think this might be implemented as an optional parameter to the
WebVRManager. Please submit a PR.

**Comment by pindiespace** [comment]
will do, thanks -pete

On Tue, Nov 17, 2015 at 9:17 AM, Boris Smus notifications@github.com
wrote:

> I think this might be implemented as an optional parameter to the
> WebVRManager. Please submit a PR.
> 
> On Mon, Nov 16, 2015 at 5:14 PM Dr. Pete Markiewicz <
> notifications@github.com> wrote:
> 
> > I've just started experimenting with the boilerplate, and ran into the
> > following issue. If VR is unavailable there may be good reasons to fall
> > back to the mono 3d canvas, embedded within a DOM element on a 2d browser
> > page. However, the resize always goes to window .innerWidth and
> > .innerHeight. So, in other words boilerplate assumes you always want to
> > fill the screen with the 3d canvas. Resizes via three.js get overridden.
> > 
> > Better Ux would allow graceful decay into a defined smaller size, as a
> > child element in markup, instead of assuming it is the only thing in the
> > page body. This is consistent with interfaces that follow "progressive
> > enhancement" and use existing markup elements as the base for building
> > the
> > VR display. -pete
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/borismus/webvr-boilerplate/issues/66.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/borismus/webvr-boilerplate/issues/66#issuecomment-157441153
> .

## 

# 

# 

_Dr. Pete Markiewicz_
_Email:_ pindiespace@gmail.com
_Sustainable virtual design blog:_
http://sustainablevirtualdesign.wordpress.com
_Sustainability template:_ http://greenboilerplate.com
_Teaching site: *http://plyojump.com http://www.plyojump.com/
*Buy my book! *- Millennials and the Popular Culture
*Lifecourse:_ http://www.lifecourse.com/store/catalog/lca/mpc.html
- AmazonAuthor Page:*
  http://www.amazon.com/Pete-Markiewicz/e/B0069VZ7BG/ref=ntt_athr_dp_pel_pop_2
  _On that page, see my DARPA Grand Challenge 2005 entry video, "Team
  Robomonster":_
  *Team Robomonster *(DARPA 2005 Grand Challenge):
  http://robotsthatjump.wordpress.com/category/team-robomonster/
  *Indiespace *(1st to sell downloaded music, March 1994):
  http://www.indiespace.com. Also see http://archive.org under
  "Kspace.com" 1996 for our original site.
  ============================================================
  =================

**Comment by bumblehead** [comment]
+1 for this change. Until a PR is accepted I have found the following to be adequate here,

``` javascript
    manager.resize_ = function () { // where "manager" is instance of WebVRManager
      this.effect.setSize(elemw, elemh);
    };
```

Buttons, however, are appended to the body of the document and do not appear in the element which parents the VR display https://github.com/borismus/webvr-boilerplate/issues/68

**Comment by pindiespace** [comment]
Working on the button issue, also a utility function seeing if element is attached to document.body or another element. Will submit PR later this week.

**Comment by bumblehead** [comment]
@pindiespace,

Thank you. Please consider making buttons and behaviour configurable. This would reduce responsibility of webvr scripts and give more control to its dependants, allowing them to do as they wish. Like this,

``` javascript
var manager = new WebVRManager(renderer, effect, {
 onRender : function (mngr) {
   var fullscreenlink = document.getElementById('fullscreenlink'),
       minscreenlink = document.getElementById('minscreenlink'),
       previouslink = document.getElementById('previouslink');

   fullscreenlink.onclick = function (e) {
     mngr.showfullscreen();

     e.preventDefault();
   };

   minscreenlink.onclick = function (e) {
     mngr.showminscreen();

     e.preventDefault();
   };

   previouslink.onclick = function (e) {
     mngr.showprevious();

     e.preventDefault();
   };
 }
});
```

**Comment by gmarinov** [comment]
we've had a similar issues on vizor.io (embedding a mono 3d view in a container), and arrived at a solution that resizes the canvas to the already-computed dimensions of its container. I'll send a PR referencing this issue, as discussed with @borismus

**Comment by pindiespace** [comment]
I've added some ideas on putting canvas and buttons into my fork.

**Comment by borismus** [comment]
Please submit a pull request.

**Comment by borismus** [comment]
Thanks for this, I've added some comments. Please take a look.

**Comment by borismus** [comment]
Using a custom canvas size should be a lot easier if you use just the webvr-polyfill to achieve it.
