### ISSUE TITLE
most recent Firefox nightly fails to animate cube after update

### ISSUE THREAD

**Issue by pindiespace** [borismus/webvr-boilerplate#70]
I updated FF on 11/30 to the most recent nightly. After applying changes, the sample index.html loads, the cube flashes momentarily - and then disappears. Buttons work fine, but no spinning cube. Same code shows the cube in Chrome and Edge.

**Comment by borismus** [comment]
cc: @caseyyee @jcarpenter

**Comment by caseyyee** [comment]
Hmm.  Seems to work for me here using 45.0a1 (2015-11-30) on Mac OS
Will check to see if others are experiencing similar issues.   

@pindiespace are you using Mac, PC or Mobile?

**Comment by pindiespace** [comment]
I'm using Windows. I've tried the non-nightly on win and mac v. 38 and it
works fine. Possibly something to do with the nightly update itself. I did
a second update this a.m. with the same result.

On Tue, Dec 1, 2015 at 5:30 PM, Casey Yee notifications@github.com wrote:

> Hmm. Seems to work for me here using 45.0a1 (2015-11-30)
> Will check to see if others are experiencing similar issues.
> 
> @pindiespace https://github.com/pindiespace are you using Mac, PC or
> Mobile?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/borismus/webvr-boilerplate/issues/70#issuecomment-161150643
> .

## 

# 

# 

_Dr. Pete Markiewicz_
_Email:_ pindiespace@gmail.com
_Sustainable virtual design blog:_
http://sustainablevirtualdesign.wordpress.com
_Sustainability template:_ http://greenboilerplate.com
_Teaching site: *http://plyojump.com http://www.plyojump.com/
*Buy my book! *- Millennials and the Popular Culture
*Lifecourse:_ http://www.lifecourse.com/store/catalog/lca/mpc.html
- AmazonAuthor Page:*
  http://www.amazon.com/Pete-Markiewicz/e/B0069VZ7BG/ref=ntt_athr_dp_pel_pop_2
  _On that page, see my DARPA Grand Challenge 2005 entry video, "Team
  Robomonster":_
  *Team Robomonster *(DARPA 2005 Grand Challenge):
  http://robotsthatjump.wordpress.com/category/team-robomonster/
  *Indiespace *(1st to sell downloaded music, March 1994):
  http://www.indiespace.com. Also see http://archive.org under
  "Kspace.com" 1996 for our original site.
  ============================================================
  =================

**Comment by pindiespace** [comment]
Required a complete uninstall of Nightly, Firefox, plus zapping appData AND files left over in Program Files. OK now...

**Comment by caseyyee** [comment]
@pindiespace Yikes!   Sounds like something a new profile may have been able to fix.   It could be that your existing/old one could have become damaged or corrupt.    For next time, try these steps to create a new one: https://developer.mozilla.org/en-US/docs/Mozilla/Multiple_Firefox_Profiles

Sorry you had to go through that.    I did do some testing and it seemed to work fine here.
