### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by ashconnell** [borismus/webvr-boilerplate#71]
The webvr-polyfill can be installed with npm, but not the boilerplate?

There is this PR, but not sure what happened to it https://github.com/borismus/webvr-boilerplate/pull/22

**Comment by borismus** [comment]
Please use bower for now. I'd rather only have one canonical way of installing this thing.

**Comment by jperl** [comment]
First of all, thank you for this amazing boilerplate - it is extremely helpful.

I hope you will reconsider using npm instead of bower.

**Comment by borismus** [comment]
The maintenance overhead is what bothers me here. If there was some way to
maintain the same version in both indices I'd be open to it.

**Comment by ashconnell** [comment]
If anything we should drop bower for npm.

We have an entire VR stack across 4 private repos using browserify and npm and this and the polyfill are the only bower dependencies that we need to hack in. We could be the only ones but I'm not sure I'm convinced.

This post explains why bower is becoming obsolete, not to mention practices around universal JavaScript it just makes sense: 

https://gofore.com/ohjelmistokehitys/stop-using-bower/

**Comment by jperl** [comment]
That's what I was thinking ^ -- bower is becoming obsolete.

**Comment by borismus** [comment]
Fair enough. Especially with npm3 I think it's a no-brainer. For the time being, would like to have this in both indices, and eventually migrate to npm. 

For the time being it would be great to have a one step version bump/tag/etc script to push to both indices. Do you know of such a thing?

**Comment by ashconnell** [comment]
`npm version` will tag and commit for you so:
1. Write code
2. `npm version`
3. `npm publish`
4. `git push`

What are you currently doing for bower?

**Comment by borismus** [comment]
That sounds reasonable.

Sadly, I don't currently have a good process. I don't even know if bower
relies on git repository tags or on versions in bower.json. I'll look at it
when back to work in early Jan.

**Comment by cvan** [comment]
I'd suggest using https://github.com/semantic-release/semantic-release for easy publishing

**Comment by ashconnell** [comment]
@cvan I wondered where that convention came from.

@borismus this should make it a lot simpler once it's set up :)

**Comment by borismus** [comment]
Thanks @cvan, but going the regular route as per @Deminetix. Never got Travis to work correctly: https://github.com/semantic-release/cli/issues/28

Now, does anyone still use bower? Really would be nice to deprecate soon.

**Comment by borismus** [comment]
Unilaterally switched to npm. Sorry bower folks, case closed.
