### ISSUE TITLE
Using alternative (camera) controller when in fullscreen mode

### ISSUE THREAD

**Issue by nylki** [borismus/webvr-boilerplate#72]
In my current projects code, I am using a modified `PointerLockControls` (http://threejs.org/examples/#misc_controls_pointerlock) , and was wondering what the best approach would be to switch to the old controls I used to have when clicking the fullscreen button. I like the behaviour of the _webvr-boilerplate_, but would simply like to use my own pointerlock controls, when no VR-gadget is connected/detected.

Do you have a recommended way of proceeding, without making the code all too ugly and breaking things?

**Comment by borismus** [comment]
You could probably use `WebVRConfig.MOUSE_KEYBOARD_CONTROLS_DISABLED`. See https://github.com/borismus/webvr-polyfill for more info.
