### ISSUE TITLE
Distortion performance and requirement

### ISSUE THREAD

**Issue by ashconnell** [borismus/webvr-boilerplate#73]
I'm running a simple scene on my Nexus 5 (Chrome beta 47.0.2526.76, Android 6.0)

Without distorter i get a consistent 60fps and with the distorter it sits ~30fps

What exactly is the distorter for? I tried on my Google Cardboard and couldn't perceive any difference apart from the bad frame-rate and a little less FOV due to the inset black area.

![With Distorter](http://i.imgur.com/D4wMRb1.png)
![Without Distorter](http://i.imgur.com/3Ys9Mcu.jpg)

**Comment by borismus** [comment]
Distortion correction undoes the distortion due to the lenses in the
viewer. In some viewers the effect is small, but in others very noticeable.

There is a more advanced and more performant way to achieve the same
results using a vertex shader.

Alternatively, you might try disabling antialiasing and see if that is a
better quality to performance trade off.

**Comment by ashconnell** [comment]
Disabling anti-aliasing bumps it up a few more fps but performance on mobile is still quite harsh even for this basic scene. I wonder how the Nexus 5 sits compared to the Nexus 5x/6p and the Galaxy s6 as this phone is coming up 2 years old

**Comment by borismus** [comment]
In my testing, WebGL perf on the Nexus 5X is basically on par with Nexus 5.
Not sure about 6P.

**Comment by mattdesl** [comment]
@borismus Can you explain the vertex shader approach a bit more?

@Deminetix Are you using device pixel ratio to scale the canvas? A basic scene that relies on `window.devicePixelRatio` (GalaxyS6 = 4) might run pretty poorly. I am using the following:

``` js
var maxDPR = 2 // usually between 2 - 3
var dpr = Math.min(maxDPR, window.devicePixelRatio)
```

**Comment by borismus** [comment]
@mattdesl The idea is to distort the vertex geometry in a shader so that no rendering to a texture is needed. Hopefully I'll be able to open source this bit of code soon.

**Comment by mattdesl** [comment]
Here is another approach I just stumbled on, worth keeping in mind. Does not yet seem possible in WebGL, but maybe WebGL2?

https://docs.google.com/presentation/d/19x9XDjUvkW_9gsfsMQzt3hZbRNziVsoCEHOn4AercAc/edit#slide=id.g5790d2a7c_066

EDIT: This is a bit off topic since it isn't to do with cardboard distortion, but more generally just left/right eye rendering.

**Comment by borismus** [comment]
Thanks. @toji might be interested.

**Comment by mattdesl** [comment]
Also see stencil rejection at 57:30 [here](http://www.gdcvault.com/play/1021771/Advanced-VR), there is a bit of talk on optimizing the "warp mesh" right after that.

Slides: http://media.steampowered.com/apps/valve/2015/Alex_Vlachos_Advanced_VR_Rendering_GDC2015.pdf

**Comment by mrdoob** [comment]
I've ported `barrel-distortion-fragment.js` to a warp mesh. I think it should be faster on mobiles. I'm not good at maths so I just tweaked the numbers until the output was the most similar. Help?

![screen shot 2015-12-20 at 00 12 23](https://cloud.githubusercontent.com/assets/97088/11917171/9d561ebe-a6b0-11e5-8f1e-c426fb1c50ed.png)

![screen shot 2015-12-20 at 00 15 37](https://cloud.githubusercontent.com/assets/97088/11917172/a42fa5d4-a6b0-11e5-8f83-205db3612775.png)

https://github.com/mrdoob/three.js/blob/dev/examples/js/effects/CardboardEffect.js

**Comment by brianpeiris** [comment]
@mrdoob Nice! I think this also fixes the mirror issue in #36

**Comment by mrdoob** [comment]
@brianpeiris It's unrelated, but yes, I've also fixed the whole `viewport`/`scissor` nightmare in `WebGLRenderer`. Now `WebGLRenderTarget` have their own.

https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderTarget.js#L19-L22

**Comment by borismus** [comment]
Great, mesh-based distortion should be much more efficient than the fragment based thing that's currently implemented. I wonder if this can all be done in a shader though?

**Comment by mrdoob** [comment]
> I wonder if this can all be done in a shader though?

Oh! In a vertex shader? So we can adjust the distortion for v1/v2 on-the-fly? Challenge accepted 😁

**Comment by borismus** [comment]
Yes, exactly! :)

**Comment by mrdoob** [comment]
You know... I think it's good as it is. Instead of computing the vertex positions every frame, it'll be more efficient to just pass the v1/v2 config to the effect constructor instead (or add a `config()` method).

**Comment by borismus** [comment]
Hmm, did you profile it? How does it compare to the current fragment-based approach? Also, have you got a link to the code/demo?

**Comment by mrdoob** [comment]
> Hmm, did you profile it?

I have not, but I would be surprised if a semi complex vertex shader is faster than a basic vertex shader.

> Also, have you got a link to the code/demo?

https://rawgit.com/mrdoob/three.js/dev/examples/webgl_effects_cardboard.html

**Comment by jzitelli** [comment]
The webgl_effects_cardboard example was crashing firefox and chrome on my Galaxy S4, seems like turning off the shadow map resolved it

**Comment by mrdoob** [comment]
Ah yes, I have to fix the shadow code still.

**Comment by jzitelli** [comment]
Seems like a nice performance improvement to me!  I hacked it into the standard webvr-boilerplate demo (still havent looked into adjusting the distortion parameters):

http://jzitelli.github.io/webvr-boilerplate/cardboardeffect/

**Comment by borismus** [comment]
This is very cool, and indeed seems more performant. Now need to port this back into the boilerplate. 

If someone has time, a pull request would be great as I'm swamped and it will take me a bit of time to get back to this.

**Comment by mrdoob** [comment]
I've (finally) just tried on my Nexus 5 and the performance improvement is very noticeable. I guess I should have added stats.js but I was lazy ;P

**Comment by borismus** [comment]
Wow, just did a profile and looks like @jzitelli's version in VR mode (~20ms per frame) runs approx. 3x faster than master (~70ms per frame!!!) on my Nexus 5X. Both are pretty much unusable.

I wonder why, but it's _way_ faster on Nexus 5 and iPhone 6.

**Comment by borismus** [comment]
By the way, you should use the code here: https://github.com/borismus/webvr-boilerplate/blob/master/src/distortion/barrel-distortion-fragment-v2.js, since it's correct. I'll remove the old one soon.

**Comment by mrdoob** [comment]
> By the way, you should use the code here: https://github.com/borismus/webvr-boilerplate/blob/master/src/distortion/barrel-distortion-fragment-v2.js, since it's correct. I'll remove the old one soon.

I think I actually used that one as reference.

**Comment by borismus** [comment]
Hmm, doesn't look like it. The shader I linked is more complex, uses projection and unprojection vectors. It's taken from the Cardboard native SDK. I'm trying to port it over into a mesh now.

**Comment by mrdoob** [comment]
The math is there, kind of... 😉 I updated `CardboardEffect`. It's now simpler code.

**Comment by borismus** [comment]
Quick update. I've ported the fragment shader into a UV-based mesh distorter. But after discussions with @mrdoob, it seems like the wrong approach. So now the challenge is to port this UV-based disorter to a vertex-based one. 

https://github.com/borismus/webvr-boilerplate/blob/uv-mesh/src/cardboard-distorter-mesh.js

**Comment by borismus** [comment]
Distortion is now handled by the WebVR polyfill, and it still uses a two pass approach, but uses a vertex shader to distort the vertices. Many thanks to @toji & @mrdoob :+1:

**Comment by mrdoob** [comment]
> Many thanks to @toji

Hey, I helped too! 😇
