### ISSUE TITLE
Depth test seems out of whack

### ISSUE THREAD

**Issue by brianchirls** [borismus/webvr-boilerplate#74]
Look what you did to the kittens!

<img width="944" alt="sadkittehs" src="https://cloud.githubusercontent.com/assets/492291/11552459/dae20b82-9952-11e5-9356-beaef70f3ef1.png">

All models and complex geometries are improperly sorted in cardboard mode. It works fine in non-VR mode or in Oculus Rift. Here's what it looks like in the same Android/Chrome browser at full-screen.

<img width="944" alt="happykittehs" src="https://cloud.githubusercontent.com/assets/492291/11552478/09a8c97e-9953-11e5-83a0-5a10dbabcd6b.png">

This problem shows up starting in v0.2.0. If I revert back to 0.1.2, it goes away.

**Comment by borismus** [comment]
Should be fixed in 0.3.0.

https://github.com/borismus/webvr-boilerplate/commit/f48f016dee7833fcf1522157e77913167f16cd7a

**Comment by brianchirls** [comment]
Ah, yes. Thanks. I was unable to test it due to another bug, which I will file shortly...
