### ISSUE TITLE
Camera position ignored in Chrome Dev 48, Nexus 5, Android 6

### ISSUE THREAD

**Issue by weddingdj** [borismus/webvr-boilerplate#76]
If I change the default position of the camera in the cube demo, it is ignored and stays at 0, 0, 0. Whereas in standard Chrome 46, Nexus 5, Android 6, the camera position is taken into account. I just added the following line to the code: camera.position.copy( new THREE.Vector3( 0, 1.7, 0 ) );

If it is an issue of Chrome or the Boilerplate, I don't know.

**Comment by borismus** [comment]
Can't reproduce.
