### ISSUE TITLE
Error in setCardboardFov_ when using Mockulus Rift

### ISSUE THREAD

**Issue by brianchirls** [borismus/webvr-boilerplate#79]
`setCardboardFov_` and `onViewerChanged_` seem to assume you are always running cardboard. If you run in a browser that supports WebVR, an error is thrown here:
https://github.com/borismus/webvr-boilerplate/blob/master/src/webvr-manager.js#L441

...because the `hmd` object does not have a `fov` property.

I left my real Oculus Rift in the office so I haven't been able to test it yet, but I assume you'll have the same problem. I'll check tomorrow or Wednesday.

**Comment by weiserhei** [comment]
I am also seeing this error with a OcR Dev Kit 2. However it does not stop the scene from working (switching in and out of VR Mode plus VR Controls work).

**Comment by borismus** [comment]
Could you try with 0.3.3, it should be resolved.

https://github.com/borismus/webvr-boilerplate/commit/f8d591ca8df86a8014e812a538cbe565133977b3

**Comment by brianchirls** [comment]
Yeah, that works much better. Quick glance at the code and it looks cleaner too. Thanks.
