### ISSUE TITLE
localStorage access should be wrapped in try..catch

### ISSUE THREAD

**Issue by brianchirls** [borismus/webvr-boilerplate#80]
I see `ViewerSelector` saves some state in `localStorage`. If the web page is loaded in an iframe and third-party cookies are disabled, any read or write access to `localStorage` will throw an error.

**Comment by borismus** [comment]
Should be fixed now.

**Comment by brianchirls** [comment]
Looks good. https://github.com/borismus/webvr-boilerplate/commit/d60117568becb0c86de77787afc1e0428ee1ff05 Thanks.
