### ISSUE TITLE
Set polyfill modules as global classes

### ISSUE THREAD

**Issue by ghost** [borismus/webvr-boilerplate#81]
I've found myself starting new projects, taking the boilerplate as base for my development because it's quite great and working by itself, saving some work from the beginning.

The only thing is that the way webvr-polyfill and webvr-manager are written, the classes are encapsulated inside the scope of the file, and can't be accessed from outside of it.

It may be easier for people to override some methods for particular purposes, and this way not alter your files, making it easier to update to new version in the future.

If you have any idea of doing this easily, please let me know.

Thanks, and keep up the good work, it's really great already!

**Comment by borismus** [comment]
Currently configuration is achieved via `WebVRConfig`. See docs in both projects. Also, there is some light API on the WebVRManager instance, which may be useful. 

What in particular are you trying to do?

**Comment by ghost** [comment]
I was trying to add some functionnalities to the MouseKeyboardPositionSensorVRDevice class in webvr-polyfill (smooth the mouse drag, add autorotation before first interaction...).
I didn't want to write directly into your file, to avoid conflicts in future updates

**Comment by borismus** [comment]
Just turn mouse + keyboard with the WebVRConfig flag and do your own
Controls.
