### ISSUE TITLE
Ios camera always start by looking opposite of the scene?

### ISSUE THREAD

**Issue by supermoos** [borismus/webvr-boilerplate#85]
Hello, I am trying to get VRControls to look at a scene, using somekind of reset / reorient function, so that I can call it and then have the scene reorient to be visible, and then apply the device orientation input from that new correctly oriented position.

VRControls.resetSensor(); kinda works, but not completely, only works when the iPhone is completely upright (in landscape though) so the volume buttons are directly parallel to the ground/earth. 
So, say I put my phone flat on the table (frontside facing me), then do a resetSensor() call, the scene doesn't appear. Where is the correct place to try and compensate for this?

**Comment by borismus** [comment]
Right now resetSensor only resets the yaw, not the pitch. Take a look in the polyfill: 

https://github.com/borismus/webvr-polyfill/blob/master/src/orientation-position-sensor-vr-device.js#L105
