### ISSUE TITLE
Listening for modechange?

### ISSUE THREAD

**Issue by RogueSheep-nl** [borismus/webvr-boilerplate#91]
Feeling kinda noobish here as I'm not quite familiar with custom events.
How do I listen for the 'modechange' event issues by the vrManager?
I've tried:
`[document|window].addEventListener('modechange', myFunc, false);`

Thanks for any pointers in the right direction.

**Comment by borismus** [comment]
The manager itself issues this event. You can observe it by calling `webVRManagerInstance.on('modechange', myFunc)`.

**Comment by RogueSheep-nl** [comment]
Thanks!
