### ISSUE TITLE
Chromium localstorage issue -Crosswalk mobile app

### ISSUE THREAD

**Issue by JohnRSim** [borismus/webvr-boilerplate#94]
https://github.com/MobileChromeApps/mobile-chrome-apps

I'm using this to develop hybrid Mobile and desktop app built with chromium/crosswalk and cordova - 
I noticed that webvr-manager uses localstorage unfortunatly this is disabled in chromium.

Could you add a check to see if this exists or if browser is chromium then swap to chromiums localstorage method?

Thanks :+1:

**Comment by JohnRSim** [comment]
```javascript
this.selectedKey = (localStorage)?localStorage.getItem(VIEWER_KEY):chrome.storage.local.get(VIEWER_KEY,function(obj) {return obj[VIEWER_KEY]}) || DEFAULT_VIEWER;

(localStorage)?localStorage.setItem(VIEWER_KEY, this.selectedKey):chrome.storage.local.set({WEBVR_CARDBOARD_VIEWER:this.selectedKey});
```

I've just added this for now for get/set to support chromium...

**Comment by borismus** [comment]
Strange that the `try...catch` block doesn't address this.

**Comment by JohnRSim** [comment]
Moved to Crosswalk and off of CCA fixed issue.
