### ISSUE TITLE
Running in cordova - label not defined. - Samsung S6

### ISSUE THREAD

**Issue by JohnRSim** [borismus/webvr-boilerplate#95]
Running in cordova I got the following error -

webvr-manager.js:633 Detected Android: GalaxyS6
webvr-manager.js:1563 Uncaught TypeError: Cannot read property 'label' of undefined

**Comment by borismus** [comment]
Why closed? What's the exact line? What version of boilerplate?

**Comment by JohnRSim** [comment]
Its to do with the localstorage not working as Im running in chromium that uses its own localstorage.. 
Fix this one - https://github.com/borismus/webvr-boilerplate/issues/94
and it will fix the label. :)

I've just hard coded line 1263: this.selectedKey =  DEFAULT_VIEWER;
At the moment.

when this.selectedKey === null then the label not defined will be displayed.

Thanks
J.
