### ISSUE TITLE
Hot updating of VR devices

### ISSUE THREAD

**Issue by brianchirls** [borismus/webvr-boilerplate#99]
I wanted to discuss this topic here a bit before proposing any implementations, so we can agree on the best user experience...

I was talking to some people at Mozilla on the WebVR slack the other day (@kearwood if I recall correctly) and they said Firefox will now report VR devices even as they are plugged in after starting the browser. And Chromium has been doing this for a while. I think we should support this for best user experience.

The first question is how to do it technically. For now, I think polling is the only way. Shouldn't be too resource-intensive to poll once every few seconds, and we could turn off polling while in VR mode. Eventually, I think the API will be extended to fire events when the equipment changes, but that could take a while, especially as updates to Chromium aren't coming every day. This would require changes to `VREffect` and `VRControls`. One of us could make a PR at three.js or fork them, which I'm considering anyway to get a quicker update.

The second question is what this looks like for the user. I think it would be helpful to indicate the change, and the name of the device that's currently in use. Not many people have multiple devices, but Chromium is still reporting the "Mockulus Rift" and it'd be nice to see confirmation that your device is working without having to check the console or jiggle it.

Any thoughts?

**Comment by ashconnell** [comment]
Yeah so polling is the only way we can currently do it in an automatic fashion.

There is also the option that - maybe when you click the VR button - it displays a list of devices. 

On mobile for example it would show cardboard v1 and v2. On desktop it would check for hmds and display that. This list could have a refresh button which re-checks hmds.

**Comment by borismus** [comment]
Brian, does this question relate to the boilerplate? For the desktop VR
case, the WebVR implementation should handle the hot updating, and I don't
really see any special role for the boilerplate.

For Cardboard, as far as I can tell, there is no concept of hot swapping,
since the VR device is your phone. If someday we have some way of
automatically switching viewers, it's something the webvr-polyfill will
need to handle (if possible).

**Comment by brianchirls** [comment]
Yes it does relate to the boilerplate, if there is any visible UI, which I think there should be. But I wanted to open that for discussion, so even if there isn't, I think it's worth talking about here. If there's no UI, then the only change necessary is in `VREffect` and `VRControls`.

If/when the WebVR API implements device installation/removal events, then yes the polyfill will need to cover that, but until then I don't think this has anything to do with the polyfill.

I agree with @Deminetix that unifying the Cardboard UI and the desktop UI is a good idea, for consistency.

I can conceive of a hot swapping scenario for Cardboard, when the actual (non-polyfill) WebVR API is in use, with the Cardboard SDK. Imagine the user loads a web page and then leaves the browser to scan a QR code on the Cardboard to set a different "viewer profile." (Perhaps they are prompted to do so by the page itself.) When the user returns to the browser, the eye translation, FOV and possibly device name will need to be updated. I don't think it's fair to expect the user to know they need to reload the page.

**Comment by borismus** [comment]
This should now be handled by WebVR 1.0 with the `onvrdisplayconnected` and `disconnected` events: https://mozvr.github.io/webvr-spec/
